/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccountStatementEntry
 */
public class AccountStatementEntryTest {
    private final AccountStatementEntry model = new AccountStatementEntry();

    /**
     * Model tests for AccountStatementEntry
     */
    @Test
    public void testAccountStatementEntry() {
        // TODO: test AccountStatementEntry
    }

    /**
     * Test the property 'annuityNumber'
     */
    @Test
    public void annuityNumberTest() {
        // TODO: test annuityNumber
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'messageDate'
     */
    @Test
    public void messageDateTest() {
        // TODO: test messageDate
    }

    /**
     * Test the property 'matchingDate'
     */
    @Test
    public void matchingDateTest() {
        // TODO: test matchingDate
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

}
