/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AutomaticBuilderOption
 */
public class AutomaticBuilderOptionTest {
    private final AutomaticBuilderOption model = new AutomaticBuilderOption();

    /**
     * Model tests for AutomaticBuilderOption
     */
    @Test
    public void testAutomaticBuilderOption() {
        // TODO: test AutomaticBuilderOption
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'investmentCurrently'
     */
    @Test
    public void investmentCurrentlyTest() {
        // TODO: test investmentCurrently
    }

    /**
     * Test the property 'totalAmountForInvestment'
     */
    @Test
    public void totalAmountForInvestmentTest() {
        // TODO: test totalAmountForInvestment
    }

    /**
     * Test the property 'originators'
     */
    @Test
    public void originatorsTest() {
        // TODO: test originators
    }

    /**
     * Test the property 'interestRateFrom'
     */
    @Test
    public void interestRateFromTest() {
        // TODO: test interestRateFrom
    }

    /**
     * Test the property 'interestRateTo'
     */
    @Test
    public void interestRateToTest() {
        // TODO: test interestRateTo
    }

    /**
     * Test the property 'maximumPerBid'
     */
    @Test
    public void maximumPerBidTest() {
        // TODO: test maximumPerBid
    }

    /**
     * Test the property 'minimumPerBid'
     */
    @Test
    public void minimumPerBidTest() {
        // TODO: test minimumPerBid
    }

    /**
     * Test the property 'reinvest'
     */
    @Test
    public void reinvestTest() {
        // TODO: test reinvest
    }

    /**
     * Test the property 'investmentLevel'
     */
    @Test
    public void investmentLevelTest() {
        // TODO: test investmentLevel
    }

    /**
     * Test the property 'secondaryMarket'
     */
    @Test
    public void secondaryMarketTest() {
        // TODO: test secondaryMarket
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'durationFrom'
     */
    @Test
    public void durationFromTest() {
        // TODO: test durationFrom
    }

    /**
     * Test the property 'durationTo'
     */
    @Test
    public void durationToTest() {
        // TODO: test durationTo
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
