/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Company
 */
public class CompanyTest {
    private final Company model = new Company();

    /**
     * Model tests for Company
     */
    @Test
    public void testCompany() {
        // TODO: test Company
    }

    /**
     * Test the property 'legalForm'
     */
    @Test
    public void legalFormTest() {
        // TODO: test legalForm
    }

    /**
     * Test the property 'yearEstablished'
     */
    @Test
    public void yearEstablishedTest() {
        // TODO: test yearEstablished
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'sector'
     */
    @Test
    public void sectorTest() {
        // TODO: test sector
    }

    /**
     * Test the property 'numberOfEmployees'
     */
    @Test
    public void numberOfEmployeesTest() {
        // TODO: test numberOfEmployees
    }

}
