/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Crif
 */
public class CrifTest {
    private final Crif model = new Crif();

    /**
     * Model tests for Crif
     */
    @Test
    public void testCrif() {
        // TODO: test Crif
    }

    /**
     * Test the property 'creditScore'
     */
    @Test
    public void creditScoreTest() {
        // TODO: test creditScore
    }

    /**
     * Test the property 'checkingDate'
     */
    @Test
    public void checkingDateTest() {
        // TODO: test checkingDate
    }

}
