/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AccountStatement;
import com.konfigthis.client.model.ActiveBid;
import com.konfigthis.client.model.AmortizationSchedule;
import com.konfigthis.client.model.Company;
import com.konfigthis.client.model.Crif;
import com.konfigthis.client.model.Expenses;
import com.konfigthis.client.model.Financial;
import com.konfigthis.client.model.Income;
import com.konfigthis.client.model.ModelPrivate;
import com.konfigthis.client.model.Questionnaire;
import com.konfigthis.client.model.TechnicalData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Loan
 */
public class LoanTest {
    private final Loan model = new Loan();

    /**
     * Model tests for Loan
     */
    @Test
    public void testLoan() {
        // TODO: test Loan
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateApproved'
     */
    @Test
    public void dateApprovedTest() {
        // TODO: test dateApproved
    }

    /**
     * Test the property 'loanAmount'
     */
    @Test
    public void loanAmountTest() {
        // TODO: test loanAmount
    }

    /**
     * Test the property 'lastPaymentDate'
     */
    @Test
    public void lastPaymentDateTest() {
        // TODO: test lastPaymentDate
    }

    /**
     * Test the property 'interestRate'
     */
    @Test
    public void interestRateTest() {
        // TODO: test interestRate
    }

    /**
     * Test the property 'paymentFrequency'
     */
    @Test
    public void paymentFrequencyTest() {
        // TODO: test paymentFrequency
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'borrowerType'
     */
    @Test
    public void borrowerTypeTest() {
        // TODO: test borrowerType
    }

    /**
     * Test the property 'biddingType'
     */
    @Test
    public void biddingTypeTest() {
        // TODO: test biddingType
    }

    /**
     * Test the property 'loanType'
     */
    @Test
    public void loanTypeTest() {
        // TODO: test loanType
    }

    /**
     * Test the property 'loanPurpose'
     */
    @Test
    public void loanPurposeTest() {
        // TODO: test loanPurpose
    }

    /**
     * Test the property 'loanRating'
     */
    @Test
    public void loanRatingTest() {
        // TODO: test loanRating
    }

    /**
     * Test the property 'loanStatus'
     */
    @Test
    public void loanStatusTest() {
        // TODO: test loanStatus
    }

    /**
     * Test the property 'performanceStatus'
     */
    @Test
    public void performanceStatusTest() {
        // TODO: test performanceStatus
    }

    /**
     * Test the property 'daysLate'
     */
    @Test
    public void daysLateTest() {
        // TODO: test daysLate
    }

    /**
     * Test the property 'collateral'
     */
    @Test
    public void collateralTest() {
        // TODO: test collateral
    }

    /**
     * Test the property 'collateralType'
     */
    @Test
    public void collateralTypeTest() {
        // TODO: test collateralType
    }

    /**
     * Test the property 'insurance'
     */
    @Test
    public void insuranceTest() {
        // TODO: test insurance
    }

    /**
     * Test the property 'totalPrincipalRemaining'
     */
    @Test
    public void totalPrincipalRemainingTest() {
        // TODO: test totalPrincipalRemaining
    }

    /**
     * Test the property 'totalRepaidPrincipal'
     */
    @Test
    public void totalRepaidPrincipalTest() {
        // TODO: test totalRepaidPrincipal
    }

    /**
     * Test the property 'totalRepaidInterest'
     */
    @Test
    public void totalRepaidInterestTest() {
        // TODO: test totalRepaidInterest
    }

    /**
     * Test the property 'biddingEnd'
     */
    @Test
    public void biddingEndTest() {
        // TODO: test biddingEnd
    }

    /**
     * Test the property 'disbursementDate'
     */
    @Test
    public void disbursementDateTest() {
        // TODO: test disbursementDate
    }

    /**
     * Test the property 'maturityDate'
     */
    @Test
    public void maturityDateTest() {
        // TODO: test maturityDate
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'bids'
     */
    @Test
    public void bidsTest() {
        // TODO: test bids
    }

    /**
     * Test the property 'borrowerPrivate'
     */
    @Test
    public void borrowerPrivateTest() {
        // TODO: test borrowerPrivate
    }

    /**
     * Test the property 'borrowerCompany'
     */
    @Test
    public void borrowerCompanyTest() {
        // TODO: test borrowerCompany
    }

    /**
     * Test the property 'income'
     */
    @Test
    public void incomeTest() {
        // TODO: test income
    }

    /**
     * Test the property 'expenses'
     */
    @Test
    public void expensesTest() {
        // TODO: test expenses
    }

    /**
     * Test the property 'crif'
     */
    @Test
    public void crifTest() {
        // TODO: test crif
    }

    /**
     * Test the property 'questionnaire'
     */
    @Test
    public void questionnaireTest() {
        // TODO: test questionnaire
    }

    /**
     * Test the property 'financial'
     */
    @Test
    public void financialTest() {
        // TODO: test financial
    }

    /**
     * Test the property 'amortizationSchedule'
     */
    @Test
    public void amortizationScheduleTest() {
        // TODO: test amortizationSchedule
    }

    /**
     * Test the property 'accountStatement'
     */
    @Test
    public void accountStatementTest() {
        // TODO: test accountStatement
    }

    /**
     * Test the property 'technicalData'
     */
    @Test
    public void technicalDataTest() {
        // TODO: test technicalData
    }

}
