/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelPrivate
 */
public class ModelPrivateTest {
    private final ModelPrivate model = new ModelPrivate();

    /**
     * Model tests for ModelPrivate
     */
    @Test
    public void testModelPrivate() {
        // TODO: test ModelPrivate
    }

    /**
     * Test the property 'borrowerId'
     */
    @Test
    public void borrowerIdTest() {
        // TODO: test borrowerId
    }

    /**
     * Test the property 'zip'
     */
    @Test
    public void zipTest() {
        // TODO: test zip
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'age'
     */
    @Test
    public void ageTest() {
        // TODO: test age
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'housingCondition'
     */
    @Test
    public void housingConditionTest() {
        // TODO: test housingCondition
    }

    /**
     * Test the property 'residentialSituation'
     */
    @Test
    public void residentialSituationTest() {
        // TODO: test residentialSituation
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'children'
     */
    @Test
    public void childrenTest() {
        // TODO: test children
    }

    /**
     * Test the property 'profession'
     */
    @Test
    public void professionTest() {
        // TODO: test profession
    }

    /**
     * Test the property 'workSince'
     */
    @Test
    public void workSinceTest() {
        // TODO: test workSince
    }

    /**
     * Test the property 'solvency'
     */
    @Test
    public void solvencyTest() {
        // TODO: test solvency
    }

    /**
     * Test the property 'monthlyNetIncome'
     */
    @Test
    public void monthlyNetIncomeTest() {
        // TODO: test monthlyNetIncome
    }

    /**
     * Test the property 'partnerIncome'
     */
    @Test
    public void partnerIncomeTest() {
        // TODO: test partnerIncome
    }

    /**
     * Test the property 'availableAmount'
     */
    @Test
    public void availableAmountTest() {
        // TODO: test availableAmount
    }

    /**
     * Test the property 'availableAmountPercentage'
     */
    @Test
    public void availableAmountPercentageTest() {
        // TODO: test availableAmountPercentage
    }

    /**
     * Test the property 'monthlyPayment'
     */
    @Test
    public void monthlyPaymentTest() {
        // TODO: test monthlyPayment
    }

    /**
     * Test the property 'collectionProcedures'
     */
    @Test
    public void collectionProceduresTest() {
        // TODO: test collectionProcedures
    }

}
