/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Investment;
import com.konfigthis.client.model.InvestorAccount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Portfolio
 */
public class PortfolioTest {
    private final Portfolio model = new Portfolio();

    /**
     * Model tests for Portfolio
     */
    @Test
    public void testPortfolio() {
        // TODO: test Portfolio
    }

    /**
     * Test the property 'investorAccount'
     */
    @Test
    public void investorAccountTest() {
        // TODO: test investorAccount
    }

    /**
     * Test the property 'investments'
     */
    @Test
    public void investmentsTest() {
        // TODO: test investments
    }

}
