/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Questionnaire
 */
public class QuestionnaireTest {
    private final Questionnaire model = new Questionnaire();

    /**
     * Model tests for Questionnaire
     */
    @Test
    public void testQuestionnaire() {
        // TODO: test Questionnaire
    }

    /**
     * Test the property 'knownIssues'
     */
    @Test
    public void knownIssuesTest() {
        // TODO: test knownIssues
    }

    /**
     * Test the property 'knownIssuesDescription'
     */
    @Test
    public void knownIssuesDescriptionTest() {
        // TODO: test knownIssuesDescription
    }

    /**
     * Test the property 'majorIssues'
     */
    @Test
    public void majorIssuesTest() {
        // TODO: test majorIssues
    }

    /**
     * Test the property 'majorIssuesDescription'
     */
    @Test
    public void majorIssuesDescriptionTest() {
        // TODO: test majorIssuesDescription
    }

    /**
     * Test the property 'financialRecovery'
     */
    @Test
    public void financialRecoveryTest() {
        // TODO: test financialRecovery
    }

    /**
     * Test the property 'financialRecoveryDescription'
     */
    @Test
    public void financialRecoveryDescriptionTest() {
        // TODO: test financialRecoveryDescription
    }

    /**
     * Test the property 'optionTeam'
     */
    @Test
    public void optionTeamTest() {
        // TODO: test optionTeam
    }

    /**
     * Test the property 'optionAudit'
     */
    @Test
    public void optionAuditTest() {
        // TODO: test optionAudit
    }

    /**
     * Test the property 'optionRevenue'
     */
    @Test
    public void optionRevenueTest() {
        // TODO: test optionRevenue
    }

    /**
     * Test the property 'optionPrice'
     */
    @Test
    public void optionPriceTest() {
        // TODO: test optionPrice
    }

    /**
     * Test the property 'marketEstimation'
     */
    @Test
    public void marketEstimationTest() {
        // TODO: test marketEstimation
    }

    /**
     * Test the property 'marketPosition'
     */
    @Test
    public void marketPositionTest() {
        // TODO: test marketPosition
    }

    /**
     * Test the property 'marketRisk'
     */
    @Test
    public void marketRiskTest() {
        // TODO: test marketRisk
    }

    /**
     * Test the property 'currentRevenue'
     */
    @Test
    public void currentRevenueTest() {
        // TODO: test currentRevenue
    }

    /**
     * Test the property 'revenueGrowth'
     */
    @Test
    public void revenueGrowthTest() {
        // TODO: test revenueGrowth
    }

    /**
     * Test the property 'ebitdaMargin'
     */
    @Test
    public void ebitdaMarginTest() {
        // TODO: test ebitdaMargin
    }

}
