/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Early repayment details
 */
@ApiModel(description = "Early repayment details")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EarlyRepayment {
  public static final String SERIALIZED_NAME_PAYMENT_DATE = "paymentDate";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DATE)
  private String paymentDate;

  public static final String SERIALIZED_NAME_PRINCIPAL_BALANCE = "principalBalance";
  @SerializedName(SERIALIZED_NAME_PRINCIPAL_BALANCE)
  private Double principalBalance;

  public static final String SERIALIZED_NAME_INTEREST = "interest";
  @SerializedName(SERIALIZED_NAME_INTEREST)
  private Double interest;

  public static final String SERIALIZED_NAME_INVESTOR_COMMISSION = "investorCommission";
  @SerializedName(SERIALIZED_NAME_INVESTOR_COMMISSION)
  private Double investorCommission;

  public static final String SERIALIZED_NAME_TOTAL_AMOUNT = "totalAmount";
  @SerializedName(SERIALIZED_NAME_TOTAL_AMOUNT)
  private Double totalAmount;

  public EarlyRepayment() {
  }

  public EarlyRepayment paymentDate(String paymentDate) {
    
    
    
    
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * date when the loan has been paid off
   * @return paymentDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12.07.2022", value = "date when the loan has been paid off")

  public String getPaymentDate() {
    return paymentDate;
  }


  public void setPaymentDate(String paymentDate) {
    
    
    
    this.paymentDate = paymentDate;
  }


  public EarlyRepayment principalBalance(Double principalBalance) {
    
    
    
    
    this.principalBalance = principalBalance;
    return this;
  }

   /**
   * the amount due and owed to satisfy the payoff of the loan
   * @return principalBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4666.77", value = "the amount due and owed to satisfy the payoff of the loan")

  public Double getPrincipalBalance() {
    return principalBalance;
  }


  public void setPrincipalBalance(Double principalBalance) {
    
    
    
    this.principalBalance = principalBalance;
  }


  public EarlyRepayment interest(Double interest) {
    
    
    
    
    this.interest = interest;
    return this;
  }

   /**
   * Gross interest amount
   * @return interest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "24.71", value = "Gross interest amount")

  public Double getInterest() {
    return interest;
  }


  public void setInterest(Double interest) {
    
    
    
    this.interest = interest;
  }


  public EarlyRepayment investorCommission(Double investorCommission) {
    
    
    
    
    this.investorCommission = investorCommission;
    return this;
  }

   /**
   * investor commission amount
   * @return investorCommission
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "investor commission amount")

  public Double getInvestorCommission() {
    return investorCommission;
  }


  public void setInvestorCommission(Double investorCommission) {
    
    
    
    this.investorCommission = investorCommission;
  }


  public EarlyRepayment totalAmount(Double totalAmount) {
    
    
    
    
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * a total amount that has been paid earlier to the investor
   * @return totalAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4690.48", value = "a total amount that has been paid earlier to the investor")

  public Double getTotalAmount() {
    return totalAmount;
  }


  public void setTotalAmount(Double totalAmount) {
    
    
    
    this.totalAmount = totalAmount;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EarlyRepayment instance itself
   */
  public EarlyRepayment putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarlyRepayment earlyRepayment = (EarlyRepayment) o;
    return Objects.equals(this.paymentDate, earlyRepayment.paymentDate) &&
        Objects.equals(this.principalBalance, earlyRepayment.principalBalance) &&
        Objects.equals(this.interest, earlyRepayment.interest) &&
        Objects.equals(this.investorCommission, earlyRepayment.investorCommission) &&
        Objects.equals(this.totalAmount, earlyRepayment.totalAmount)&&
        Objects.equals(this.additionalProperties, earlyRepayment.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentDate, principalBalance, interest, investorCommission, totalAmount, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarlyRepayment {\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    principalBalance: ").append(toIndentedString(principalBalance)).append("\n");
    sb.append("    interest: ").append(toIndentedString(interest)).append("\n");
    sb.append("    investorCommission: ").append(toIndentedString(investorCommission)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("paymentDate");
    openapiFields.add("principalBalance");
    openapiFields.add("interest");
    openapiFields.add("investorCommission");
    openapiFields.add("totalAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EarlyRepayment
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EarlyRepayment.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EarlyRepayment is not found in the empty JSON string", EarlyRepayment.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("paymentDate").isJsonNull() && (jsonObj.get("paymentDate") != null && !jsonObj.get("paymentDate").isJsonNull()) && !jsonObj.get("paymentDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentDate").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EarlyRepayment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EarlyRepayment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EarlyRepayment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EarlyRepayment.class));

       return (TypeAdapter<T>) new TypeAdapter<EarlyRepayment>() {
           @Override
           public void write(JsonWriter out, EarlyRepayment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EarlyRepayment read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EarlyRepayment instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EarlyRepayment given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EarlyRepayment
  * @throws IOException if the JSON string is invalid with respect to EarlyRepayment
  */
  public static EarlyRepayment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EarlyRepayment.class);
  }

 /**
  * Convert an instance of EarlyRepayment to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

