/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Company financial data in the last two years
 */
@ApiModel(description = "Company financial data in the last two years")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Financial {
  public static final String SERIALIZED_NAME_LIQUID_FUNDS_YEAR1 = "liquidFunds_Year1";
  @SerializedName(SERIALIZED_NAME_LIQUID_FUNDS_YEAR1)
  private Double liquidFundsYear1;

  public static final String SERIALIZED_NAME_LIQUID_FUNDS_YEAR2 = "liquidFunds_Year2";
  @SerializedName(SERIALIZED_NAME_LIQUID_FUNDS_YEAR2)
  private Double liquidFundsYear2;

  public static final String SERIALIZED_NAME_ACCOUNTS_RECEIVABLE_YEAR1 = "accountsReceivable_Year1";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS_RECEIVABLE_YEAR1)
  private Double accountsReceivableYear1;

  public static final String SERIALIZED_NAME_ACCOUNTS_RECEIVABLE_YEAR2 = "accountsReceivable_Year2";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS_RECEIVABLE_YEAR2)
  private Double accountsReceivableYear2;

  public static final String SERIALIZED_NAME_STOCKS_YEAR1 = "stocks_Year1";
  @SerializedName(SERIALIZED_NAME_STOCKS_YEAR1)
  private Double stocksYear1;

  public static final String SERIALIZED_NAME_STOCKS_YEAR2 = "stocks_Year2";
  @SerializedName(SERIALIZED_NAME_STOCKS_YEAR2)
  private Double stocksYear2;

  public static final String SERIALIZED_NAME_CURRENT_ASSETS_OTHER_YEAR1 = "currentAssets_Other_Year1";
  @SerializedName(SERIALIZED_NAME_CURRENT_ASSETS_OTHER_YEAR1)
  private Double currentAssetsOtherYear1;

  public static final String SERIALIZED_NAME_CURRENT_ASSETS_OTHER_YEAR2 = "currentAssets_Other_Year2";
  @SerializedName(SERIALIZED_NAME_CURRENT_ASSETS_OTHER_YEAR2)
  private Double currentAssetsOtherYear2;

  public static final String SERIALIZED_NAME_CURRENT_ASSETS_YEAR1_S_U_M = "currentAssets_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_CURRENT_ASSETS_YEAR1_S_U_M)
  private Double currentAssetsYear1SUM;

  public static final String SERIALIZED_NAME_CURRENT_ASSETS_YEAR2_S_U_M = "currentAssets_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_CURRENT_ASSETS_YEAR2_S_U_M)
  private Double currentAssetsYear2SUM;

  public static final String SERIALIZED_NAME_MACHINES_AND_SYSTEMS_YEAR1 = "machinesAndSystems_Year1";
  @SerializedName(SERIALIZED_NAME_MACHINES_AND_SYSTEMS_YEAR1)
  private Double machinesAndSystemsYear1;

  public static final String SERIALIZED_NAME_MACHINES_AND_SYSTEMS_YEAR2 = "machinesAndSystems_Year2";
  @SerializedName(SERIALIZED_NAME_MACHINES_AND_SYSTEMS_YEAR2)
  private Double machinesAndSystemsYear2;

  public static final String SERIALIZED_NAME_FACILITIES_AND_VEHICLE_PARK_YEAR1 = "facilitiesAndVehiclePark_Year1";
  @SerializedName(SERIALIZED_NAME_FACILITIES_AND_VEHICLE_PARK_YEAR1)
  private Double facilitiesAndVehicleParkYear1;

  public static final String SERIALIZED_NAME_FACILITIES_AND_VEHICLE_PARK_YEAR2 = "facilitiesAndVehiclePark_Year2";
  @SerializedName(SERIALIZED_NAME_FACILITIES_AND_VEHICLE_PARK_YEAR2)
  private Double facilitiesAndVehicleParkYear2;

  public static final String SERIALIZED_NAME_FIXED_ASSETS_OTHER_YEAR1 = "fixedAssets_Other_Year1";
  @SerializedName(SERIALIZED_NAME_FIXED_ASSETS_OTHER_YEAR1)
  private Double fixedAssetsOtherYear1;

  public static final String SERIALIZED_NAME_FIXED_ASSETS_OTHER_YEAR2 = "fixedAssets_Other_Year2";
  @SerializedName(SERIALIZED_NAME_FIXED_ASSETS_OTHER_YEAR2)
  private Double fixedAssetsOtherYear2;

  public static final String SERIALIZED_NAME_FIXED_ASSETS_YEAR1_S_U_M = "fixedAssets_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_FIXED_ASSETS_YEAR1_S_U_M)
  private Double fixedAssetsYear1SUM;

  public static final String SERIALIZED_NAME_FIXED_ASSETS_YEAR2_S_U_M = "fixedAssets_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_FIXED_ASSETS_YEAR2_S_U_M)
  private Double fixedAssetsYear2SUM;

  public static final String SERIALIZED_NAME_ACCOUNTS_PAYABLE_YEAR1 = "accountsPayable_Year1";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS_PAYABLE_YEAR1)
  private Double accountsPayableYear1;

  public static final String SERIALIZED_NAME_ACCOUNTS_PAYABLE_YEAR2 = "accountsPayable_Year2";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS_PAYABLE_YEAR2)
  private Double accountsPayableYear2;

  public static final String SERIALIZED_NAME_TOTAL_ASSETS_YEAR1 = "totalAssets_Year1";
  @SerializedName(SERIALIZED_NAME_TOTAL_ASSETS_YEAR1)
  private Double totalAssetsYear1;

  public static final String SERIALIZED_NAME_TOTAL_ASSETS_YEAR2 = "totalAssets_Year2";
  @SerializedName(SERIALIZED_NAME_TOTAL_ASSETS_YEAR2)
  private Double totalAssetsYear2;

  public static final String SERIALIZED_NAME_SHORT_TERM_LOANS_YEAR1 = "shortTermLoans_Year1";
  @SerializedName(SERIALIZED_NAME_SHORT_TERM_LOANS_YEAR1)
  private Double shortTermLoansYear1;

  public static final String SERIALIZED_NAME_SHORT_TERM_LOANS_YEAR2 = "shortTermLoans_Year2";
  @SerializedName(SERIALIZED_NAME_SHORT_TERM_LOANS_YEAR2)
  private Double shortTermLoansYear2;

  public static final String SERIALIZED_NAME_CURENT_LIABILITIES_OTHER_YEAR1 = "curentLiabilities_Other_Year1";
  @SerializedName(SERIALIZED_NAME_CURENT_LIABILITIES_OTHER_YEAR1)
  private Double curentLiabilitiesOtherYear1;

  public static final String SERIALIZED_NAME_CURENT_LIABILITIES_OTHER_YEAR2 = "curentLiabilities_Other_Year2";
  @SerializedName(SERIALIZED_NAME_CURENT_LIABILITIES_OTHER_YEAR2)
  private Double curentLiabilitiesOtherYear2;

  public static final String SERIALIZED_NAME_CURENT_LIABILITIES_YEAR1_S_U_M = "curentLiabilities_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_CURENT_LIABILITIES_YEAR1_S_U_M)
  private Double curentLiabilitiesYear1SUM;

  public static final String SERIALIZED_NAME_CURENT_LIABILITIES_YEAR2_S_U_M = "curentLiabilities_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_CURENT_LIABILITIES_YEAR2_S_U_M)
  private Double curentLiabilitiesYear2SUM;

  public static final String SERIALIZED_NAME_LONG_TERM_LOANS_YEAR1 = "longTermLoans_Year1";
  @SerializedName(SERIALIZED_NAME_LONG_TERM_LOANS_YEAR1)
  private Double longTermLoansYear1;

  public static final String SERIALIZED_NAME_LONG_TERM_LOANS_YEAR2 = "longTermLoans_Year2";
  @SerializedName(SERIALIZED_NAME_LONG_TERM_LOANS_YEAR2)
  private Double longTermLoansYear2;

  public static final String SERIALIZED_NAME_ACCRUALS_YEAR1 = "accruals_Year1";
  @SerializedName(SERIALIZED_NAME_ACCRUALS_YEAR1)
  private Double accrualsYear1;

  public static final String SERIALIZED_NAME_ACCRUALS_YEAR2 = "accruals_Year2";
  @SerializedName(SERIALIZED_NAME_ACCRUALS_YEAR2)
  private Double accrualsYear2;

  public static final String SERIALIZED_NAME_LONG_TERM_LIABILITIES_OTHER_YEAR1 = "longTermLiabilities_Other_Year1";
  @SerializedName(SERIALIZED_NAME_LONG_TERM_LIABILITIES_OTHER_YEAR1)
  private Double longTermLiabilitiesOtherYear1;

  public static final String SERIALIZED_NAME_LONG_TERM_LIABILITIES_OTHER_YEAR2 = "longTermLiabilities_Other_Year2";
  @SerializedName(SERIALIZED_NAME_LONG_TERM_LIABILITIES_OTHER_YEAR2)
  private Double longTermLiabilitiesOtherYear2;

  public static final String SERIALIZED_NAME_LONG_TERM_LIABILITIES_YEAR1_S_U_M = "longTermLiabilities_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_LONG_TERM_LIABILITIES_YEAR1_S_U_M)
  private Double longTermLiabilitiesYear1SUM;

  public static final String SERIALIZED_NAME_LONG_TERM_LIABILITIES_YEAR2_S_U_M = "longTermLiabilities_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_LONG_TERM_LIABILITIES_YEAR2_S_U_M)
  private Double longTermLiabilitiesYear2SUM;

  public static final String SERIALIZED_NAME_EQUITY_YEAR1 = "equity_Year1";
  @SerializedName(SERIALIZED_NAME_EQUITY_YEAR1)
  private Double equityYear1;

  public static final String SERIALIZED_NAME_EQUITY_YEAR2 = "equity_Year2";
  @SerializedName(SERIALIZED_NAME_EQUITY_YEAR2)
  private Double equityYear2;

  public static final String SERIALIZED_NAME_TOTAL_LIABILITIES_YEAR1_S_U_M = "totalLiabilities_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_TOTAL_LIABILITIES_YEAR1_S_U_M)
  private Double totalLiabilitiesYear1SUM;

  public static final String SERIALIZED_NAME_TOTAL_LIABILITIES_YEAR2_S_U_M = "totalLiabilities_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_TOTAL_LIABILITIES_YEAR2_S_U_M)
  private Double totalLiabilitiesYear2SUM;

  public static final String SERIALIZED_NAME_SALES_PROCEEDS_YEAR1 = "salesProceeds_Year1";
  @SerializedName(SERIALIZED_NAME_SALES_PROCEEDS_YEAR1)
  private Double salesProceedsYear1;

  public static final String SERIALIZED_NAME_SALES_PROCEEDS_YEAR2 = "salesProceeds_Year2";
  @SerializedName(SERIALIZED_NAME_SALES_PROCEEDS_YEAR2)
  private Double salesProceedsYear2;

  public static final String SERIALIZED_NAME_COST_OF_GOODS_YEAR1 = "costOfGoods_Year1";
  @SerializedName(SERIALIZED_NAME_COST_OF_GOODS_YEAR1)
  private Double costOfGoodsYear1;

  public static final String SERIALIZED_NAME_COST_OF_GOODS_YEAR2 = "costOfGoods_Year2";
  @SerializedName(SERIALIZED_NAME_COST_OF_GOODS_YEAR2)
  private Double costOfGoodsYear2;

  public static final String SERIALIZED_NAME_GROSS_PROFIT_YEAR1_S_U_M = "grossProfit_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_GROSS_PROFIT_YEAR1_S_U_M)
  private Double grossProfitYear1SUM;

  public static final String SERIALIZED_NAME_GROSS_PROFIT_YEAR2_S_U_M = "grossProfit_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_GROSS_PROFIT_YEAR2_S_U_M)
  private Double grossProfitYear2SUM;

  public static final String SERIALIZED_NAME_OPERATING_EXPENSES_YEAR1 = "operatingExpenses_Year1";
  @SerializedName(SERIALIZED_NAME_OPERATING_EXPENSES_YEAR1)
  private Double operatingExpensesYear1;

  public static final String SERIALIZED_NAME_OPERATING_EXPENSES_YEAR2 = "operatingExpenses_Year2";
  @SerializedName(SERIALIZED_NAME_OPERATING_EXPENSES_YEAR2)
  private Double operatingExpensesYear2;

  public static final String SERIALIZED_NAME_EBIDTA_YEAR1_S_U_M = "ebidta_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_EBIDTA_YEAR1_S_U_M)
  private Double ebidtaYear1SUM;

  public static final String SERIALIZED_NAME_EBIDTA_YEAR2_S_U_M = "ebidta_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_EBIDTA_YEAR2_S_U_M)
  private Double ebidtaYear2SUM;

  public static final String SERIALIZED_NAME_DEPRECIATION_YEAR1 = "depreciation_Year1";
  @SerializedName(SERIALIZED_NAME_DEPRECIATION_YEAR1)
  private Double depreciationYear1;

  public static final String SERIALIZED_NAME_DEPRECIATION_YEAR2 = "depreciation_Year2";
  @SerializedName(SERIALIZED_NAME_DEPRECIATION_YEAR2)
  private Double depreciationYear2;

  public static final String SERIALIZED_NAME_EBIT_YEAR1_S_U_M = "ebit_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_EBIT_YEAR1_S_U_M)
  private Double ebitYear1SUM;

  public static final String SERIALIZED_NAME_EBIT_YEAR2_S_U_M = "ebit_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_EBIT_YEAR2_S_U_M)
  private Double ebitYear2SUM;

  public static final String SERIALIZED_NAME_FINANCIAL_EXPENSES_YEAR1 = "financialExpenses_Year1";
  @SerializedName(SERIALIZED_NAME_FINANCIAL_EXPENSES_YEAR1)
  private Double financialExpensesYear1;

  public static final String SERIALIZED_NAME_FINANCIAL_EXPENSES_YEAR2 = "financialExpenses_Year2";
  @SerializedName(SERIALIZED_NAME_FINANCIAL_EXPENSES_YEAR2)
  private Double financialExpensesYear2;

  public static final String SERIALIZED_NAME_NET_INCOME_BEFORE_TAXES_YEAR1_S_U_M = "netIncomeBeforeTaxes_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_NET_INCOME_BEFORE_TAXES_YEAR1_S_U_M)
  private Double netIncomeBeforeTaxesYear1SUM;

  public static final String SERIALIZED_NAME_NET_INCOME_BEFORE_TAXES_YEAR2_S_U_M = "netIncomeBeforeTaxes_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_NET_INCOME_BEFORE_TAXES_YEAR2_S_U_M)
  private Double netIncomeBeforeTaxesYear2SUM;

  public static final String SERIALIZED_NAME_INCOME_TAXES_YEAR1 = "incomeTaxes_Year1";
  @SerializedName(SERIALIZED_NAME_INCOME_TAXES_YEAR1)
  private Double incomeTaxesYear1;

  public static final String SERIALIZED_NAME_INCOME_TAXES_YEAR2 = "incomeTaxes_Year2";
  @SerializedName(SERIALIZED_NAME_INCOME_TAXES_YEAR2)
  private Double incomeTaxesYear2;

  public static final String SERIALIZED_NAME_NET_PROFIT_YEAR1_S_U_M = "netProfit_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_NET_PROFIT_YEAR1_S_U_M)
  private Double netProfitYear1SUM;

  public static final String SERIALIZED_NAME_NET_PROFIT_YEAR2_S_U_M = "netProfit_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_NET_PROFIT_YEAR2_S_U_M)
  private Double netProfitYear2SUM;

  public static final String SERIALIZED_NAME_BEGINNING_OF_YEAR_FINANCIALS_YEAR1 = "beginningOfYearFinancials_Year1";
  @SerializedName(SERIALIZED_NAME_BEGINNING_OF_YEAR_FINANCIALS_YEAR1)
  private Double beginningOfYearFinancialsYear1;

  public static final String SERIALIZED_NAME_BEGINNING_OF_YEAR_FINANCIALS_YEAR2 = "beginningOfYearFinancials_Year2";
  @SerializedName(SERIALIZED_NAME_BEGINNING_OF_YEAR_FINANCIALS_YEAR2)
  private Double beginningOfYearFinancialsYear2;

  public static final String SERIALIZED_NAME_CASH_FLOW_OPERATING_YEAR1 = "cashFlowOperating_Year1";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_OPERATING_YEAR1)
  private Double cashFlowOperatingYear1;

  public static final String SERIALIZED_NAME_CASH_FLOW_OPERATING_YEAR2 = "cashFlowOperating_Year2";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_OPERATING_YEAR2)
  private Double cashFlowOperatingYear2;

  public static final String SERIALIZED_NAME_CASH_FLOW_INVESTING_YEAR1 = "cashFlowInvesting_Year1";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_INVESTING_YEAR1)
  private Double cashFlowInvestingYear1;

  public static final String SERIALIZED_NAME_CASH_FLOW_INVESTING_YEAR2 = "cashFlowInvesting_Year2";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_INVESTING_YEAR2)
  private Double cashFlowInvestingYear2;

  public static final String SERIALIZED_NAME_CASH_FLOW_FINANCING_YEAR1 = "cashFlowFinancing_Year1";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_FINANCING_YEAR1)
  private Double cashFlowFinancingYear1;

  public static final String SERIALIZED_NAME_CASH_FLOW_FINANCING_YEAR2 = "cashFlowFinancing_Year2";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_FINANCING_YEAR2)
  private Double cashFlowFinancingYear2;

  public static final String SERIALIZED_NAME_CASH_FLOW_YEAR1_S_U_M = "cashFlow_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_YEAR1_S_U_M)
  private Double cashFlowYear1SUM;

  public static final String SERIALIZED_NAME_CASH_FLOW_YEAR2_S_U_M = "cashFlow_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_CASH_FLOW_YEAR2_S_U_M)
  private Double cashFlowYear2SUM;

  public static final String SERIALIZED_NAME_END_OF_YEAR_FINANCIALS_YEAR1_S_U_M = "endOfYearFinancials_Year1_SUM";
  @SerializedName(SERIALIZED_NAME_END_OF_YEAR_FINANCIALS_YEAR1_S_U_M)
  private Double endOfYearFinancialsYear1SUM;

  public static final String SERIALIZED_NAME_END_OF_YEAR_FINANCIALS_YEAR2_S_U_M = "endOfYearFinancials_Year2_SUM";
  @SerializedName(SERIALIZED_NAME_END_OF_YEAR_FINANCIALS_YEAR2_S_U_M)
  private Double endOfYearFinancialsYear2SUM;

  public Financial() {
  }

  public Financial liquidFundsYear1(Double liquidFundsYear1) {
    
    
    
    
    this.liquidFundsYear1 = liquidFundsYear1;
    return this;
  }

   /**
   * Liquid funds at the end of Year 1
   * @return liquidFundsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Liquid funds at the end of Year 1")

  public Double getLiquidFundsYear1() {
    return liquidFundsYear1;
  }


  public void setLiquidFundsYear1(Double liquidFundsYear1) {
    
    
    
    this.liquidFundsYear1 = liquidFundsYear1;
  }


  public Financial liquidFundsYear2(Double liquidFundsYear2) {
    
    
    
    
    this.liquidFundsYear2 = liquidFundsYear2;
    return this;
  }

   /**
   * Liquid funds at the end of Year 2
   * @return liquidFundsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Liquid funds at the end of Year 2")

  public Double getLiquidFundsYear2() {
    return liquidFundsYear2;
  }


  public void setLiquidFundsYear2(Double liquidFundsYear2) {
    
    
    
    this.liquidFundsYear2 = liquidFundsYear2;
  }


  public Financial accountsReceivableYear1(Double accountsReceivableYear1) {
    
    
    
    
    this.accountsReceivableYear1 = accountsReceivableYear1;
    return this;
  }

   /**
   * Accounts receivable at the end of Year 1
   * @return accountsReceivableYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Accounts receivable at the end of Year 1")

  public Double getAccountsReceivableYear1() {
    return accountsReceivableYear1;
  }


  public void setAccountsReceivableYear1(Double accountsReceivableYear1) {
    
    
    
    this.accountsReceivableYear1 = accountsReceivableYear1;
  }


  public Financial accountsReceivableYear2(Double accountsReceivableYear2) {
    
    
    
    
    this.accountsReceivableYear2 = accountsReceivableYear2;
    return this;
  }

   /**
   * Accounts receivable at the end of Year 2
   * @return accountsReceivableYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Accounts receivable at the end of Year 2")

  public Double getAccountsReceivableYear2() {
    return accountsReceivableYear2;
  }


  public void setAccountsReceivableYear2(Double accountsReceivableYear2) {
    
    
    
    this.accountsReceivableYear2 = accountsReceivableYear2;
  }


  public Financial stocksYear1(Double stocksYear1) {
    
    
    
    
    this.stocksYear1 = stocksYear1;
    return this;
  }

   /**
   * Stocks at the end of Year 1
   * @return stocksYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Stocks at the end of Year 1")

  public Double getStocksYear1() {
    return stocksYear1;
  }


  public void setStocksYear1(Double stocksYear1) {
    
    
    
    this.stocksYear1 = stocksYear1;
  }


  public Financial stocksYear2(Double stocksYear2) {
    
    
    
    
    this.stocksYear2 = stocksYear2;
    return this;
  }

   /**
   * Stocks at the end of Year 2
   * @return stocksYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Stocks at the end of Year 2")

  public Double getStocksYear2() {
    return stocksYear2;
  }


  public void setStocksYear2(Double stocksYear2) {
    
    
    
    this.stocksYear2 = stocksYear2;
  }


  public Financial currentAssetsOtherYear1(Double currentAssetsOtherYear1) {
    
    
    
    
    this.currentAssetsOtherYear1 = currentAssetsOtherYear1;
    return this;
  }

   /**
   * Other current assets at the end of Year 1
   * @return currentAssetsOtherYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other current assets at the end of Year 1")

  public Double getCurrentAssetsOtherYear1() {
    return currentAssetsOtherYear1;
  }


  public void setCurrentAssetsOtherYear1(Double currentAssetsOtherYear1) {
    
    
    
    this.currentAssetsOtherYear1 = currentAssetsOtherYear1;
  }


  public Financial currentAssetsOtherYear2(Double currentAssetsOtherYear2) {
    
    
    
    
    this.currentAssetsOtherYear2 = currentAssetsOtherYear2;
    return this;
  }

   /**
   * Other current assets at the end of Year 2
   * @return currentAssetsOtherYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other current assets at the end of Year 2")

  public Double getCurrentAssetsOtherYear2() {
    return currentAssetsOtherYear2;
  }


  public void setCurrentAssetsOtherYear2(Double currentAssetsOtherYear2) {
    
    
    
    this.currentAssetsOtherYear2 = currentAssetsOtherYear2;
  }


  public Financial currentAssetsYear1SUM(Double currentAssetsYear1SUM) {
    
    
    
    
    this.currentAssetsYear1SUM = currentAssetsYear1SUM;
    return this;
  }

   /**
   * Total current assets at the end of Year 1
   * @return currentAssetsYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total current assets at the end of Year 1")

  public Double getCurrentAssetsYear1SUM() {
    return currentAssetsYear1SUM;
  }


  public void setCurrentAssetsYear1SUM(Double currentAssetsYear1SUM) {
    
    
    
    this.currentAssetsYear1SUM = currentAssetsYear1SUM;
  }


  public Financial currentAssetsYear2SUM(Double currentAssetsYear2SUM) {
    
    
    
    
    this.currentAssetsYear2SUM = currentAssetsYear2SUM;
    return this;
  }

   /**
   * Total current assets at the end of Year 2
   * @return currentAssetsYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total current assets at the end of Year 2")

  public Double getCurrentAssetsYear2SUM() {
    return currentAssetsYear2SUM;
  }


  public void setCurrentAssetsYear2SUM(Double currentAssetsYear2SUM) {
    
    
    
    this.currentAssetsYear2SUM = currentAssetsYear2SUM;
  }


  public Financial machinesAndSystemsYear1(Double machinesAndSystemsYear1) {
    
    
    
    
    this.machinesAndSystemsYear1 = machinesAndSystemsYear1;
    return this;
  }

   /**
   * Machines and systems at the end of Year 1
   * @return machinesAndSystemsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Machines and systems at the end of Year 1")

  public Double getMachinesAndSystemsYear1() {
    return machinesAndSystemsYear1;
  }


  public void setMachinesAndSystemsYear1(Double machinesAndSystemsYear1) {
    
    
    
    this.machinesAndSystemsYear1 = machinesAndSystemsYear1;
  }


  public Financial machinesAndSystemsYear2(Double machinesAndSystemsYear2) {
    
    
    
    
    this.machinesAndSystemsYear2 = machinesAndSystemsYear2;
    return this;
  }

   /**
   * Machines and systems at the end of Year 2
   * @return machinesAndSystemsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Machines and systems at the end of Year 2")

  public Double getMachinesAndSystemsYear2() {
    return machinesAndSystemsYear2;
  }


  public void setMachinesAndSystemsYear2(Double machinesAndSystemsYear2) {
    
    
    
    this.machinesAndSystemsYear2 = machinesAndSystemsYear2;
  }


  public Financial facilitiesAndVehicleParkYear1(Double facilitiesAndVehicleParkYear1) {
    
    
    
    
    this.facilitiesAndVehicleParkYear1 = facilitiesAndVehicleParkYear1;
    return this;
  }

   /**
   * Facilities and vehicle at the end of Year 1
   * @return facilitiesAndVehicleParkYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Facilities and vehicle at the end of Year 1")

  public Double getFacilitiesAndVehicleParkYear1() {
    return facilitiesAndVehicleParkYear1;
  }


  public void setFacilitiesAndVehicleParkYear1(Double facilitiesAndVehicleParkYear1) {
    
    
    
    this.facilitiesAndVehicleParkYear1 = facilitiesAndVehicleParkYear1;
  }


  public Financial facilitiesAndVehicleParkYear2(Double facilitiesAndVehicleParkYear2) {
    
    
    
    
    this.facilitiesAndVehicleParkYear2 = facilitiesAndVehicleParkYear2;
    return this;
  }

   /**
   * Facilities and vehicle at the end of Year 2
   * @return facilitiesAndVehicleParkYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Facilities and vehicle at the end of Year 2")

  public Double getFacilitiesAndVehicleParkYear2() {
    return facilitiesAndVehicleParkYear2;
  }


  public void setFacilitiesAndVehicleParkYear2(Double facilitiesAndVehicleParkYear2) {
    
    
    
    this.facilitiesAndVehicleParkYear2 = facilitiesAndVehicleParkYear2;
  }


  public Financial fixedAssetsOtherYear1(Double fixedAssetsOtherYear1) {
    
    
    
    
    this.fixedAssetsOtherYear1 = fixedAssetsOtherYear1;
    return this;
  }

   /**
   * Other fixed assets at the end of Year 1
   * @return fixedAssetsOtherYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other fixed assets at the end of Year 1")

  public Double getFixedAssetsOtherYear1() {
    return fixedAssetsOtherYear1;
  }


  public void setFixedAssetsOtherYear1(Double fixedAssetsOtherYear1) {
    
    
    
    this.fixedAssetsOtherYear1 = fixedAssetsOtherYear1;
  }


  public Financial fixedAssetsOtherYear2(Double fixedAssetsOtherYear2) {
    
    
    
    
    this.fixedAssetsOtherYear2 = fixedAssetsOtherYear2;
    return this;
  }

   /**
   * Other fixed assets at the end of Year 2
   * @return fixedAssetsOtherYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other fixed assets at the end of Year 2")

  public Double getFixedAssetsOtherYear2() {
    return fixedAssetsOtherYear2;
  }


  public void setFixedAssetsOtherYear2(Double fixedAssetsOtherYear2) {
    
    
    
    this.fixedAssetsOtherYear2 = fixedAssetsOtherYear2;
  }


  public Financial fixedAssetsYear1SUM(Double fixedAssetsYear1SUM) {
    
    
    
    
    this.fixedAssetsYear1SUM = fixedAssetsYear1SUM;
    return this;
  }

   /**
   * Total fixed assets at the end of Year 1
   * @return fixedAssetsYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total fixed assets at the end of Year 1")

  public Double getFixedAssetsYear1SUM() {
    return fixedAssetsYear1SUM;
  }


  public void setFixedAssetsYear1SUM(Double fixedAssetsYear1SUM) {
    
    
    
    this.fixedAssetsYear1SUM = fixedAssetsYear1SUM;
  }


  public Financial fixedAssetsYear2SUM(Double fixedAssetsYear2SUM) {
    
    
    
    
    this.fixedAssetsYear2SUM = fixedAssetsYear2SUM;
    return this;
  }

   /**
   * Total fixed assets at the end of Year 2
   * @return fixedAssetsYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total fixed assets at the end of Year 2")

  public Double getFixedAssetsYear2SUM() {
    return fixedAssetsYear2SUM;
  }


  public void setFixedAssetsYear2SUM(Double fixedAssetsYear2SUM) {
    
    
    
    this.fixedAssetsYear2SUM = fixedAssetsYear2SUM;
  }


  public Financial accountsPayableYear1(Double accountsPayableYear1) {
    
    
    
    
    this.accountsPayableYear1 = accountsPayableYear1;
    return this;
  }

   /**
   * Accounts payable at the end of Year 1
   * @return accountsPayableYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Accounts payable at the end of Year 1")

  public Double getAccountsPayableYear1() {
    return accountsPayableYear1;
  }


  public void setAccountsPayableYear1(Double accountsPayableYear1) {
    
    
    
    this.accountsPayableYear1 = accountsPayableYear1;
  }


  public Financial accountsPayableYear2(Double accountsPayableYear2) {
    
    
    
    
    this.accountsPayableYear2 = accountsPayableYear2;
    return this;
  }

   /**
   * Accounts payable at the end of Year 2
   * @return accountsPayableYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Accounts payable at the end of Year 2")

  public Double getAccountsPayableYear2() {
    return accountsPayableYear2;
  }


  public void setAccountsPayableYear2(Double accountsPayableYear2) {
    
    
    
    this.accountsPayableYear2 = accountsPayableYear2;
  }


  public Financial totalAssetsYear1(Double totalAssetsYear1) {
    
    
    
    
    this.totalAssetsYear1 = totalAssetsYear1;
    return this;
  }

   /**
   * Total assets at the end of Year 1
   * @return totalAssetsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total assets at the end of Year 1")

  public Double getTotalAssetsYear1() {
    return totalAssetsYear1;
  }


  public void setTotalAssetsYear1(Double totalAssetsYear1) {
    
    
    
    this.totalAssetsYear1 = totalAssetsYear1;
  }


  public Financial totalAssetsYear2(Double totalAssetsYear2) {
    
    
    
    
    this.totalAssetsYear2 = totalAssetsYear2;
    return this;
  }

   /**
   * Total assets at the end of Year 2
   * @return totalAssetsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total assets at the end of Year 2")

  public Double getTotalAssetsYear2() {
    return totalAssetsYear2;
  }


  public void setTotalAssetsYear2(Double totalAssetsYear2) {
    
    
    
    this.totalAssetsYear2 = totalAssetsYear2;
  }


  public Financial shortTermLoansYear1(Double shortTermLoansYear1) {
    
    
    
    
    this.shortTermLoansYear1 = shortTermLoansYear1;
    return this;
  }

   /**
   * Short term loans at the end of Year 1
   * @return shortTermLoansYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Short term loans at the end of Year 1")

  public Double getShortTermLoansYear1() {
    return shortTermLoansYear1;
  }


  public void setShortTermLoansYear1(Double shortTermLoansYear1) {
    
    
    
    this.shortTermLoansYear1 = shortTermLoansYear1;
  }


  public Financial shortTermLoansYear2(Double shortTermLoansYear2) {
    
    
    
    
    this.shortTermLoansYear2 = shortTermLoansYear2;
    return this;
  }

   /**
   * Short term loans at the end of Year 2
   * @return shortTermLoansYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Short term loans at the end of Year 2")

  public Double getShortTermLoansYear2() {
    return shortTermLoansYear2;
  }


  public void setShortTermLoansYear2(Double shortTermLoansYear2) {
    
    
    
    this.shortTermLoansYear2 = shortTermLoansYear2;
  }


  public Financial curentLiabilitiesOtherYear1(Double curentLiabilitiesOtherYear1) {
    
    
    
    
    this.curentLiabilitiesOtherYear1 = curentLiabilitiesOtherYear1;
    return this;
  }

   /**
   * Other current liabilities at the end of Year 1
   * @return curentLiabilitiesOtherYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other current liabilities at the end of Year 1")

  public Double getCurentLiabilitiesOtherYear1() {
    return curentLiabilitiesOtherYear1;
  }


  public void setCurentLiabilitiesOtherYear1(Double curentLiabilitiesOtherYear1) {
    
    
    
    this.curentLiabilitiesOtherYear1 = curentLiabilitiesOtherYear1;
  }


  public Financial curentLiabilitiesOtherYear2(Double curentLiabilitiesOtherYear2) {
    
    
    
    
    this.curentLiabilitiesOtherYear2 = curentLiabilitiesOtherYear2;
    return this;
  }

   /**
   * Other current liabilities at the end of Year 2
   * @return curentLiabilitiesOtherYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other current liabilities at the end of Year 2")

  public Double getCurentLiabilitiesOtherYear2() {
    return curentLiabilitiesOtherYear2;
  }


  public void setCurentLiabilitiesOtherYear2(Double curentLiabilitiesOtherYear2) {
    
    
    
    this.curentLiabilitiesOtherYear2 = curentLiabilitiesOtherYear2;
  }


  public Financial curentLiabilitiesYear1SUM(Double curentLiabilitiesYear1SUM) {
    
    
    
    
    this.curentLiabilitiesYear1SUM = curentLiabilitiesYear1SUM;
    return this;
  }

   /**
   * Total current liabilities at the end of Year 1
   * @return curentLiabilitiesYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total current liabilities at the end of Year 1")

  public Double getCurentLiabilitiesYear1SUM() {
    return curentLiabilitiesYear1SUM;
  }


  public void setCurentLiabilitiesYear1SUM(Double curentLiabilitiesYear1SUM) {
    
    
    
    this.curentLiabilitiesYear1SUM = curentLiabilitiesYear1SUM;
  }


  public Financial curentLiabilitiesYear2SUM(Double curentLiabilitiesYear2SUM) {
    
    
    
    
    this.curentLiabilitiesYear2SUM = curentLiabilitiesYear2SUM;
    return this;
  }

   /**
   * Total current liabilities at the end of Year 2
   * @return curentLiabilitiesYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total current liabilities at the end of Year 2")

  public Double getCurentLiabilitiesYear2SUM() {
    return curentLiabilitiesYear2SUM;
  }


  public void setCurentLiabilitiesYear2SUM(Double curentLiabilitiesYear2SUM) {
    
    
    
    this.curentLiabilitiesYear2SUM = curentLiabilitiesYear2SUM;
  }


  public Financial longTermLoansYear1(Double longTermLoansYear1) {
    
    
    
    
    this.longTermLoansYear1 = longTermLoansYear1;
    return this;
  }

   /**
   * Long term loans at the end of Year 1
   * @return longTermLoansYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Long term loans at the end of Year 1")

  public Double getLongTermLoansYear1() {
    return longTermLoansYear1;
  }


  public void setLongTermLoansYear1(Double longTermLoansYear1) {
    
    
    
    this.longTermLoansYear1 = longTermLoansYear1;
  }


  public Financial longTermLoansYear2(Double longTermLoansYear2) {
    
    
    
    
    this.longTermLoansYear2 = longTermLoansYear2;
    return this;
  }

   /**
   * Long term loans at the end of Year 2
   * @return longTermLoansYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Long term loans at the end of Year 2")

  public Double getLongTermLoansYear2() {
    return longTermLoansYear2;
  }


  public void setLongTermLoansYear2(Double longTermLoansYear2) {
    
    
    
    this.longTermLoansYear2 = longTermLoansYear2;
  }


  public Financial accrualsYear1(Double accrualsYear1) {
    
    
    
    
    this.accrualsYear1 = accrualsYear1;
    return this;
  }

   /**
   * Accruals at the end of Year 1
   * @return accrualsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Accruals at the end of Year 1")

  public Double getAccrualsYear1() {
    return accrualsYear1;
  }


  public void setAccrualsYear1(Double accrualsYear1) {
    
    
    
    this.accrualsYear1 = accrualsYear1;
  }


  public Financial accrualsYear2(Double accrualsYear2) {
    
    
    
    
    this.accrualsYear2 = accrualsYear2;
    return this;
  }

   /**
   * Accruals at the end of Year 2
   * @return accrualsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Accruals at the end of Year 2")

  public Double getAccrualsYear2() {
    return accrualsYear2;
  }


  public void setAccrualsYear2(Double accrualsYear2) {
    
    
    
    this.accrualsYear2 = accrualsYear2;
  }


  public Financial longTermLiabilitiesOtherYear1(Double longTermLiabilitiesOtherYear1) {
    
    
    
    
    this.longTermLiabilitiesOtherYear1 = longTermLiabilitiesOtherYear1;
    return this;
  }

   /**
   * Other long term laiabilities at the end of Year 1
   * @return longTermLiabilitiesOtherYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other long term laiabilities at the end of Year 1")

  public Double getLongTermLiabilitiesOtherYear1() {
    return longTermLiabilitiesOtherYear1;
  }


  public void setLongTermLiabilitiesOtherYear1(Double longTermLiabilitiesOtherYear1) {
    
    
    
    this.longTermLiabilitiesOtherYear1 = longTermLiabilitiesOtherYear1;
  }


  public Financial longTermLiabilitiesOtherYear2(Double longTermLiabilitiesOtherYear2) {
    
    
    
    
    this.longTermLiabilitiesOtherYear2 = longTermLiabilitiesOtherYear2;
    return this;
  }

   /**
   * Other long term laiabilities at the end of Year 2
   * @return longTermLiabilitiesOtherYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other long term laiabilities at the end of Year 2")

  public Double getLongTermLiabilitiesOtherYear2() {
    return longTermLiabilitiesOtherYear2;
  }


  public void setLongTermLiabilitiesOtherYear2(Double longTermLiabilitiesOtherYear2) {
    
    
    
    this.longTermLiabilitiesOtherYear2 = longTermLiabilitiesOtherYear2;
  }


  public Financial longTermLiabilitiesYear1SUM(Double longTermLiabilitiesYear1SUM) {
    
    
    
    
    this.longTermLiabilitiesYear1SUM = longTermLiabilitiesYear1SUM;
    return this;
  }

   /**
   * Total long term laiabilities at the end of Year 1
   * @return longTermLiabilitiesYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total long term laiabilities at the end of Year 1")

  public Double getLongTermLiabilitiesYear1SUM() {
    return longTermLiabilitiesYear1SUM;
  }


  public void setLongTermLiabilitiesYear1SUM(Double longTermLiabilitiesYear1SUM) {
    
    
    
    this.longTermLiabilitiesYear1SUM = longTermLiabilitiesYear1SUM;
  }


  public Financial longTermLiabilitiesYear2SUM(Double longTermLiabilitiesYear2SUM) {
    
    
    
    
    this.longTermLiabilitiesYear2SUM = longTermLiabilitiesYear2SUM;
    return this;
  }

   /**
   * Total long term laiabilities at the end of Year 2
   * @return longTermLiabilitiesYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total long term laiabilities at the end of Year 2")

  public Double getLongTermLiabilitiesYear2SUM() {
    return longTermLiabilitiesYear2SUM;
  }


  public void setLongTermLiabilitiesYear2SUM(Double longTermLiabilitiesYear2SUM) {
    
    
    
    this.longTermLiabilitiesYear2SUM = longTermLiabilitiesYear2SUM;
  }


  public Financial equityYear1(Double equityYear1) {
    
    
    
    
    this.equityYear1 = equityYear1;
    return this;
  }

   /**
   * Equity at the end of Year 1
   * @return equityYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Equity at the end of Year 1")

  public Double getEquityYear1() {
    return equityYear1;
  }


  public void setEquityYear1(Double equityYear1) {
    
    
    
    this.equityYear1 = equityYear1;
  }


  public Financial equityYear2(Double equityYear2) {
    
    
    
    
    this.equityYear2 = equityYear2;
    return this;
  }

   /**
   * Equity at the end of Year 2
   * @return equityYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Equity at the end of Year 2")

  public Double getEquityYear2() {
    return equityYear2;
  }


  public void setEquityYear2(Double equityYear2) {
    
    
    
    this.equityYear2 = equityYear2;
  }


  public Financial totalLiabilitiesYear1SUM(Double totalLiabilitiesYear1SUM) {
    
    
    
    
    this.totalLiabilitiesYear1SUM = totalLiabilitiesYear1SUM;
    return this;
  }

   /**
   * Total laiabilitie at the end of Year 1
   * @return totalLiabilitiesYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total laiabilitie at the end of Year 1")

  public Double getTotalLiabilitiesYear1SUM() {
    return totalLiabilitiesYear1SUM;
  }


  public void setTotalLiabilitiesYear1SUM(Double totalLiabilitiesYear1SUM) {
    
    
    
    this.totalLiabilitiesYear1SUM = totalLiabilitiesYear1SUM;
  }


  public Financial totalLiabilitiesYear2SUM(Double totalLiabilitiesYear2SUM) {
    
    
    
    
    this.totalLiabilitiesYear2SUM = totalLiabilitiesYear2SUM;
    return this;
  }

   /**
   * Total laiabilitie at the end of Year 2
   * @return totalLiabilitiesYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total laiabilitie at the end of Year 2")

  public Double getTotalLiabilitiesYear2SUM() {
    return totalLiabilitiesYear2SUM;
  }


  public void setTotalLiabilitiesYear2SUM(Double totalLiabilitiesYear2SUM) {
    
    
    
    this.totalLiabilitiesYear2SUM = totalLiabilitiesYear2SUM;
  }


  public Financial salesProceedsYear1(Double salesProceedsYear1) {
    
    
    
    
    this.salesProceedsYear1 = salesProceedsYear1;
    return this;
  }

   /**
   * Sales Year 1
   * @return salesProceedsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sales Year 1")

  public Double getSalesProceedsYear1() {
    return salesProceedsYear1;
  }


  public void setSalesProceedsYear1(Double salesProceedsYear1) {
    
    
    
    this.salesProceedsYear1 = salesProceedsYear1;
  }


  public Financial salesProceedsYear2(Double salesProceedsYear2) {
    
    
    
    
    this.salesProceedsYear2 = salesProceedsYear2;
    return this;
  }

   /**
   * Sales Year 2
   * @return salesProceedsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sales Year 2")

  public Double getSalesProceedsYear2() {
    return salesProceedsYear2;
  }


  public void setSalesProceedsYear2(Double salesProceedsYear2) {
    
    
    
    this.salesProceedsYear2 = salesProceedsYear2;
  }


  public Financial costOfGoodsYear1(Double costOfGoodsYear1) {
    
    
    
    
    this.costOfGoodsYear1 = costOfGoodsYear1;
    return this;
  }

   /**
   * Cost of goods Year 1
   * @return costOfGoodsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cost of goods Year 1")

  public Double getCostOfGoodsYear1() {
    return costOfGoodsYear1;
  }


  public void setCostOfGoodsYear1(Double costOfGoodsYear1) {
    
    
    
    this.costOfGoodsYear1 = costOfGoodsYear1;
  }


  public Financial costOfGoodsYear2(Double costOfGoodsYear2) {
    
    
    
    
    this.costOfGoodsYear2 = costOfGoodsYear2;
    return this;
  }

   /**
   * Cost of goods Year 2
   * @return costOfGoodsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cost of goods Year 2")

  public Double getCostOfGoodsYear2() {
    return costOfGoodsYear2;
  }


  public void setCostOfGoodsYear2(Double costOfGoodsYear2) {
    
    
    
    this.costOfGoodsYear2 = costOfGoodsYear2;
  }


  public Financial grossProfitYear1SUM(Double grossProfitYear1SUM) {
    
    
    
    
    this.grossProfitYear1SUM = grossProfitYear1SUM;
    return this;
  }

   /**
   * Gross profit Year 1
   * @return grossProfitYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gross profit Year 1")

  public Double getGrossProfitYear1SUM() {
    return grossProfitYear1SUM;
  }


  public void setGrossProfitYear1SUM(Double grossProfitYear1SUM) {
    
    
    
    this.grossProfitYear1SUM = grossProfitYear1SUM;
  }


  public Financial grossProfitYear2SUM(Double grossProfitYear2SUM) {
    
    
    
    
    this.grossProfitYear2SUM = grossProfitYear2SUM;
    return this;
  }

   /**
   * Gross profit Year 2
   * @return grossProfitYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gross profit Year 2")

  public Double getGrossProfitYear2SUM() {
    return grossProfitYear2SUM;
  }


  public void setGrossProfitYear2SUM(Double grossProfitYear2SUM) {
    
    
    
    this.grossProfitYear2SUM = grossProfitYear2SUM;
  }


  public Financial operatingExpensesYear1(Double operatingExpensesYear1) {
    
    
    
    
    this.operatingExpensesYear1 = operatingExpensesYear1;
    return this;
  }

   /**
   * Operating expenses Year 1
   * @return operatingExpensesYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Operating expenses Year 1")

  public Double getOperatingExpensesYear1() {
    return operatingExpensesYear1;
  }


  public void setOperatingExpensesYear1(Double operatingExpensesYear1) {
    
    
    
    this.operatingExpensesYear1 = operatingExpensesYear1;
  }


  public Financial operatingExpensesYear2(Double operatingExpensesYear2) {
    
    
    
    
    this.operatingExpensesYear2 = operatingExpensesYear2;
    return this;
  }

   /**
   * Operating expenses Year 2
   * @return operatingExpensesYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Operating expenses Year 2")

  public Double getOperatingExpensesYear2() {
    return operatingExpensesYear2;
  }


  public void setOperatingExpensesYear2(Double operatingExpensesYear2) {
    
    
    
    this.operatingExpensesYear2 = operatingExpensesYear2;
  }


  public Financial ebidtaYear1SUM(Double ebidtaYear1SUM) {
    
    
    
    
    this.ebidtaYear1SUM = ebidtaYear1SUM;
    return this;
  }

   /**
   * Ebidta Year 1
   * @return ebidtaYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ebidta Year 1")

  public Double getEbidtaYear1SUM() {
    return ebidtaYear1SUM;
  }


  public void setEbidtaYear1SUM(Double ebidtaYear1SUM) {
    
    
    
    this.ebidtaYear1SUM = ebidtaYear1SUM;
  }


  public Financial ebidtaYear2SUM(Double ebidtaYear2SUM) {
    
    
    
    
    this.ebidtaYear2SUM = ebidtaYear2SUM;
    return this;
  }

   /**
   * Ebidta Year 2
   * @return ebidtaYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ebidta Year 2")

  public Double getEbidtaYear2SUM() {
    return ebidtaYear2SUM;
  }


  public void setEbidtaYear2SUM(Double ebidtaYear2SUM) {
    
    
    
    this.ebidtaYear2SUM = ebidtaYear2SUM;
  }


  public Financial depreciationYear1(Double depreciationYear1) {
    
    
    
    
    this.depreciationYear1 = depreciationYear1;
    return this;
  }

   /**
   * Depreciation Year 1
   * @return depreciationYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Depreciation Year 1")

  public Double getDepreciationYear1() {
    return depreciationYear1;
  }


  public void setDepreciationYear1(Double depreciationYear1) {
    
    
    
    this.depreciationYear1 = depreciationYear1;
  }


  public Financial depreciationYear2(Double depreciationYear2) {
    
    
    
    
    this.depreciationYear2 = depreciationYear2;
    return this;
  }

   /**
   * Depreciation Year 2
   * @return depreciationYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Depreciation Year 2")

  public Double getDepreciationYear2() {
    return depreciationYear2;
  }


  public void setDepreciationYear2(Double depreciationYear2) {
    
    
    
    this.depreciationYear2 = depreciationYear2;
  }


  public Financial ebitYear1SUM(Double ebitYear1SUM) {
    
    
    
    
    this.ebitYear1SUM = ebitYear1SUM;
    return this;
  }

   /**
   * Ebit Year 1
   * @return ebitYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ebit Year 1")

  public Double getEbitYear1SUM() {
    return ebitYear1SUM;
  }


  public void setEbitYear1SUM(Double ebitYear1SUM) {
    
    
    
    this.ebitYear1SUM = ebitYear1SUM;
  }


  public Financial ebitYear2SUM(Double ebitYear2SUM) {
    
    
    
    
    this.ebitYear2SUM = ebitYear2SUM;
    return this;
  }

   /**
   * Ebit Year 2
   * @return ebitYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ebit Year 2")

  public Double getEbitYear2SUM() {
    return ebitYear2SUM;
  }


  public void setEbitYear2SUM(Double ebitYear2SUM) {
    
    
    
    this.ebitYear2SUM = ebitYear2SUM;
  }


  public Financial financialExpensesYear1(Double financialExpensesYear1) {
    
    
    
    
    this.financialExpensesYear1 = financialExpensesYear1;
    return this;
  }

   /**
   * Financial expenses Year 1
   * @return financialExpensesYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Financial expenses Year 1")

  public Double getFinancialExpensesYear1() {
    return financialExpensesYear1;
  }


  public void setFinancialExpensesYear1(Double financialExpensesYear1) {
    
    
    
    this.financialExpensesYear1 = financialExpensesYear1;
  }


  public Financial financialExpensesYear2(Double financialExpensesYear2) {
    
    
    
    
    this.financialExpensesYear2 = financialExpensesYear2;
    return this;
  }

   /**
   * Financial expenses Year 2
   * @return financialExpensesYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Financial expenses Year 2")

  public Double getFinancialExpensesYear2() {
    return financialExpensesYear2;
  }


  public void setFinancialExpensesYear2(Double financialExpensesYear2) {
    
    
    
    this.financialExpensesYear2 = financialExpensesYear2;
  }


  public Financial netIncomeBeforeTaxesYear1SUM(Double netIncomeBeforeTaxesYear1SUM) {
    
    
    
    
    this.netIncomeBeforeTaxesYear1SUM = netIncomeBeforeTaxesYear1SUM;
    return this;
  }

   /**
   * Net income before tax Year 1
   * @return netIncomeBeforeTaxesYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Net income before tax Year 1")

  public Double getNetIncomeBeforeTaxesYear1SUM() {
    return netIncomeBeforeTaxesYear1SUM;
  }


  public void setNetIncomeBeforeTaxesYear1SUM(Double netIncomeBeforeTaxesYear1SUM) {
    
    
    
    this.netIncomeBeforeTaxesYear1SUM = netIncomeBeforeTaxesYear1SUM;
  }


  public Financial netIncomeBeforeTaxesYear2SUM(Double netIncomeBeforeTaxesYear2SUM) {
    
    
    
    
    this.netIncomeBeforeTaxesYear2SUM = netIncomeBeforeTaxesYear2SUM;
    return this;
  }

   /**
   * Net income before tax Year 2
   * @return netIncomeBeforeTaxesYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Net income before tax Year 2")

  public Double getNetIncomeBeforeTaxesYear2SUM() {
    return netIncomeBeforeTaxesYear2SUM;
  }


  public void setNetIncomeBeforeTaxesYear2SUM(Double netIncomeBeforeTaxesYear2SUM) {
    
    
    
    this.netIncomeBeforeTaxesYear2SUM = netIncomeBeforeTaxesYear2SUM;
  }


  public Financial incomeTaxesYear1(Double incomeTaxesYear1) {
    
    
    
    
    this.incomeTaxesYear1 = incomeTaxesYear1;
    return this;
  }

   /**
   * Income taxes Year 1
   * @return incomeTaxesYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Income taxes Year 1")

  public Double getIncomeTaxesYear1() {
    return incomeTaxesYear1;
  }


  public void setIncomeTaxesYear1(Double incomeTaxesYear1) {
    
    
    
    this.incomeTaxesYear1 = incomeTaxesYear1;
  }


  public Financial incomeTaxesYear2(Double incomeTaxesYear2) {
    
    
    
    
    this.incomeTaxesYear2 = incomeTaxesYear2;
    return this;
  }

   /**
   * Income taxes Year 2
   * @return incomeTaxesYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Income taxes Year 2")

  public Double getIncomeTaxesYear2() {
    return incomeTaxesYear2;
  }


  public void setIncomeTaxesYear2(Double incomeTaxesYear2) {
    
    
    
    this.incomeTaxesYear2 = incomeTaxesYear2;
  }


  public Financial netProfitYear1SUM(Double netProfitYear1SUM) {
    
    
    
    
    this.netProfitYear1SUM = netProfitYear1SUM;
    return this;
  }

   /**
   * Net profit Year 1
   * @return netProfitYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Net profit Year 1")

  public Double getNetProfitYear1SUM() {
    return netProfitYear1SUM;
  }


  public void setNetProfitYear1SUM(Double netProfitYear1SUM) {
    
    
    
    this.netProfitYear1SUM = netProfitYear1SUM;
  }


  public Financial netProfitYear2SUM(Double netProfitYear2SUM) {
    
    
    
    
    this.netProfitYear2SUM = netProfitYear2SUM;
    return this;
  }

   /**
   * Net profit Year 2
   * @return netProfitYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Net profit Year 2")

  public Double getNetProfitYear2SUM() {
    return netProfitYear2SUM;
  }


  public void setNetProfitYear2SUM(Double netProfitYear2SUM) {
    
    
    
    this.netProfitYear2SUM = netProfitYear2SUM;
  }


  public Financial beginningOfYearFinancialsYear1(Double beginningOfYearFinancialsYear1) {
    
    
    
    
    this.beginningOfYearFinancialsYear1 = beginningOfYearFinancialsYear1;
    return this;
  }

   /**
   * Financials at the beginning of Year 1
   * @return beginningOfYearFinancialsYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Financials at the beginning of Year 1")

  public Double getBeginningOfYearFinancialsYear1() {
    return beginningOfYearFinancialsYear1;
  }


  public void setBeginningOfYearFinancialsYear1(Double beginningOfYearFinancialsYear1) {
    
    
    
    this.beginningOfYearFinancialsYear1 = beginningOfYearFinancialsYear1;
  }


  public Financial beginningOfYearFinancialsYear2(Double beginningOfYearFinancialsYear2) {
    
    
    
    
    this.beginningOfYearFinancialsYear2 = beginningOfYearFinancialsYear2;
    return this;
  }

   /**
   * Financials at the beginning of Year 2
   * @return beginningOfYearFinancialsYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Financials at the beginning of Year 2")

  public Double getBeginningOfYearFinancialsYear2() {
    return beginningOfYearFinancialsYear2;
  }


  public void setBeginningOfYearFinancialsYear2(Double beginningOfYearFinancialsYear2) {
    
    
    
    this.beginningOfYearFinancialsYear2 = beginningOfYearFinancialsYear2;
  }


  public Financial cashFlowOperatingYear1(Double cashFlowOperatingYear1) {
    
    
    
    
    this.cashFlowOperatingYear1 = cashFlowOperatingYear1;
    return this;
  }

   /**
   * Cash flow of operating activities Year 1
   * @return cashFlowOperatingYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cash flow of operating activities Year 1")

  public Double getCashFlowOperatingYear1() {
    return cashFlowOperatingYear1;
  }


  public void setCashFlowOperatingYear1(Double cashFlowOperatingYear1) {
    
    
    
    this.cashFlowOperatingYear1 = cashFlowOperatingYear1;
  }


  public Financial cashFlowOperatingYear2(Double cashFlowOperatingYear2) {
    
    
    
    
    this.cashFlowOperatingYear2 = cashFlowOperatingYear2;
    return this;
  }

   /**
   * Cash flow of operating activities Year 2
   * @return cashFlowOperatingYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cash flow of operating activities Year 2")

  public Double getCashFlowOperatingYear2() {
    return cashFlowOperatingYear2;
  }


  public void setCashFlowOperatingYear2(Double cashFlowOperatingYear2) {
    
    
    
    this.cashFlowOperatingYear2 = cashFlowOperatingYear2;
  }


  public Financial cashFlowInvestingYear1(Double cashFlowInvestingYear1) {
    
    
    
    
    this.cashFlowInvestingYear1 = cashFlowInvestingYear1;
    return this;
  }

   /**
   * Cash flow of investing activities Year 1
   * @return cashFlowInvestingYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cash flow of investing activities Year 1")

  public Double getCashFlowInvestingYear1() {
    return cashFlowInvestingYear1;
  }


  public void setCashFlowInvestingYear1(Double cashFlowInvestingYear1) {
    
    
    
    this.cashFlowInvestingYear1 = cashFlowInvestingYear1;
  }


  public Financial cashFlowInvestingYear2(Double cashFlowInvestingYear2) {
    
    
    
    
    this.cashFlowInvestingYear2 = cashFlowInvestingYear2;
    return this;
  }

   /**
   * Cash flow of investing activities Year 2
   * @return cashFlowInvestingYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cash flow of investing activities Year 2")

  public Double getCashFlowInvestingYear2() {
    return cashFlowInvestingYear2;
  }


  public void setCashFlowInvestingYear2(Double cashFlowInvestingYear2) {
    
    
    
    this.cashFlowInvestingYear2 = cashFlowInvestingYear2;
  }


  public Financial cashFlowFinancingYear1(Double cashFlowFinancingYear1) {
    
    
    
    
    this.cashFlowFinancingYear1 = cashFlowFinancingYear1;
    return this;
  }

   /**
   * Cash flow of finansing activities Year 1
   * @return cashFlowFinancingYear1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cash flow of finansing activities Year 1")

  public Double getCashFlowFinancingYear1() {
    return cashFlowFinancingYear1;
  }


  public void setCashFlowFinancingYear1(Double cashFlowFinancingYear1) {
    
    
    
    this.cashFlowFinancingYear1 = cashFlowFinancingYear1;
  }


  public Financial cashFlowFinancingYear2(Double cashFlowFinancingYear2) {
    
    
    
    
    this.cashFlowFinancingYear2 = cashFlowFinancingYear2;
    return this;
  }

   /**
   * Cash flow of finansing activities Year 2
   * @return cashFlowFinancingYear2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cash flow of finansing activities Year 2")

  public Double getCashFlowFinancingYear2() {
    return cashFlowFinancingYear2;
  }


  public void setCashFlowFinancingYear2(Double cashFlowFinancingYear2) {
    
    
    
    this.cashFlowFinancingYear2 = cashFlowFinancingYear2;
  }


  public Financial cashFlowYear1SUM(Double cashFlowYear1SUM) {
    
    
    
    
    this.cashFlowYear1SUM = cashFlowYear1SUM;
    return this;
  }

   /**
   * Total cash flow Year 1
   * @return cashFlowYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total cash flow Year 1")

  public Double getCashFlowYear1SUM() {
    return cashFlowYear1SUM;
  }


  public void setCashFlowYear1SUM(Double cashFlowYear1SUM) {
    
    
    
    this.cashFlowYear1SUM = cashFlowYear1SUM;
  }


  public Financial cashFlowYear2SUM(Double cashFlowYear2SUM) {
    
    
    
    
    this.cashFlowYear2SUM = cashFlowYear2SUM;
    return this;
  }

   /**
   * Total cash flow Year 2
   * @return cashFlowYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total cash flow Year 2")

  public Double getCashFlowYear2SUM() {
    return cashFlowYear2SUM;
  }


  public void setCashFlowYear2SUM(Double cashFlowYear2SUM) {
    
    
    
    this.cashFlowYear2SUM = cashFlowYear2SUM;
  }


  public Financial endOfYearFinancialsYear1SUM(Double endOfYearFinancialsYear1SUM) {
    
    
    
    
    this.endOfYearFinancialsYear1SUM = endOfYearFinancialsYear1SUM;
    return this;
  }

   /**
   * Financials at the end of Year 1
   * @return endOfYearFinancialsYear1SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Financials at the end of Year 1")

  public Double getEndOfYearFinancialsYear1SUM() {
    return endOfYearFinancialsYear1SUM;
  }


  public void setEndOfYearFinancialsYear1SUM(Double endOfYearFinancialsYear1SUM) {
    
    
    
    this.endOfYearFinancialsYear1SUM = endOfYearFinancialsYear1SUM;
  }


  public Financial endOfYearFinancialsYear2SUM(Double endOfYearFinancialsYear2SUM) {
    
    
    
    
    this.endOfYearFinancialsYear2SUM = endOfYearFinancialsYear2SUM;
    return this;
  }

   /**
   * Financials at the end of Year 2
   * @return endOfYearFinancialsYear2SUM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Financials at the end of Year 2")

  public Double getEndOfYearFinancialsYear2SUM() {
    return endOfYearFinancialsYear2SUM;
  }


  public void setEndOfYearFinancialsYear2SUM(Double endOfYearFinancialsYear2SUM) {
    
    
    
    this.endOfYearFinancialsYear2SUM = endOfYearFinancialsYear2SUM;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Financial instance itself
   */
  public Financial putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Financial financial = (Financial) o;
    return Objects.equals(this.liquidFundsYear1, financial.liquidFundsYear1) &&
        Objects.equals(this.liquidFundsYear2, financial.liquidFundsYear2) &&
        Objects.equals(this.accountsReceivableYear1, financial.accountsReceivableYear1) &&
        Objects.equals(this.accountsReceivableYear2, financial.accountsReceivableYear2) &&
        Objects.equals(this.stocksYear1, financial.stocksYear1) &&
        Objects.equals(this.stocksYear2, financial.stocksYear2) &&
        Objects.equals(this.currentAssetsOtherYear1, financial.currentAssetsOtherYear1) &&
        Objects.equals(this.currentAssetsOtherYear2, financial.currentAssetsOtherYear2) &&
        Objects.equals(this.currentAssetsYear1SUM, financial.currentAssetsYear1SUM) &&
        Objects.equals(this.currentAssetsYear2SUM, financial.currentAssetsYear2SUM) &&
        Objects.equals(this.machinesAndSystemsYear1, financial.machinesAndSystemsYear1) &&
        Objects.equals(this.machinesAndSystemsYear2, financial.machinesAndSystemsYear2) &&
        Objects.equals(this.facilitiesAndVehicleParkYear1, financial.facilitiesAndVehicleParkYear1) &&
        Objects.equals(this.facilitiesAndVehicleParkYear2, financial.facilitiesAndVehicleParkYear2) &&
        Objects.equals(this.fixedAssetsOtherYear1, financial.fixedAssetsOtherYear1) &&
        Objects.equals(this.fixedAssetsOtherYear2, financial.fixedAssetsOtherYear2) &&
        Objects.equals(this.fixedAssetsYear1SUM, financial.fixedAssetsYear1SUM) &&
        Objects.equals(this.fixedAssetsYear2SUM, financial.fixedAssetsYear2SUM) &&
        Objects.equals(this.accountsPayableYear1, financial.accountsPayableYear1) &&
        Objects.equals(this.accountsPayableYear2, financial.accountsPayableYear2) &&
        Objects.equals(this.totalAssetsYear1, financial.totalAssetsYear1) &&
        Objects.equals(this.totalAssetsYear2, financial.totalAssetsYear2) &&
        Objects.equals(this.shortTermLoansYear1, financial.shortTermLoansYear1) &&
        Objects.equals(this.shortTermLoansYear2, financial.shortTermLoansYear2) &&
        Objects.equals(this.curentLiabilitiesOtherYear1, financial.curentLiabilitiesOtherYear1) &&
        Objects.equals(this.curentLiabilitiesOtherYear2, financial.curentLiabilitiesOtherYear2) &&
        Objects.equals(this.curentLiabilitiesYear1SUM, financial.curentLiabilitiesYear1SUM) &&
        Objects.equals(this.curentLiabilitiesYear2SUM, financial.curentLiabilitiesYear2SUM) &&
        Objects.equals(this.longTermLoansYear1, financial.longTermLoansYear1) &&
        Objects.equals(this.longTermLoansYear2, financial.longTermLoansYear2) &&
        Objects.equals(this.accrualsYear1, financial.accrualsYear1) &&
        Objects.equals(this.accrualsYear2, financial.accrualsYear2) &&
        Objects.equals(this.longTermLiabilitiesOtherYear1, financial.longTermLiabilitiesOtherYear1) &&
        Objects.equals(this.longTermLiabilitiesOtherYear2, financial.longTermLiabilitiesOtherYear2) &&
        Objects.equals(this.longTermLiabilitiesYear1SUM, financial.longTermLiabilitiesYear1SUM) &&
        Objects.equals(this.longTermLiabilitiesYear2SUM, financial.longTermLiabilitiesYear2SUM) &&
        Objects.equals(this.equityYear1, financial.equityYear1) &&
        Objects.equals(this.equityYear2, financial.equityYear2) &&
        Objects.equals(this.totalLiabilitiesYear1SUM, financial.totalLiabilitiesYear1SUM) &&
        Objects.equals(this.totalLiabilitiesYear2SUM, financial.totalLiabilitiesYear2SUM) &&
        Objects.equals(this.salesProceedsYear1, financial.salesProceedsYear1) &&
        Objects.equals(this.salesProceedsYear2, financial.salesProceedsYear2) &&
        Objects.equals(this.costOfGoodsYear1, financial.costOfGoodsYear1) &&
        Objects.equals(this.costOfGoodsYear2, financial.costOfGoodsYear2) &&
        Objects.equals(this.grossProfitYear1SUM, financial.grossProfitYear1SUM) &&
        Objects.equals(this.grossProfitYear2SUM, financial.grossProfitYear2SUM) &&
        Objects.equals(this.operatingExpensesYear1, financial.operatingExpensesYear1) &&
        Objects.equals(this.operatingExpensesYear2, financial.operatingExpensesYear2) &&
        Objects.equals(this.ebidtaYear1SUM, financial.ebidtaYear1SUM) &&
        Objects.equals(this.ebidtaYear2SUM, financial.ebidtaYear2SUM) &&
        Objects.equals(this.depreciationYear1, financial.depreciationYear1) &&
        Objects.equals(this.depreciationYear2, financial.depreciationYear2) &&
        Objects.equals(this.ebitYear1SUM, financial.ebitYear1SUM) &&
        Objects.equals(this.ebitYear2SUM, financial.ebitYear2SUM) &&
        Objects.equals(this.financialExpensesYear1, financial.financialExpensesYear1) &&
        Objects.equals(this.financialExpensesYear2, financial.financialExpensesYear2) &&
        Objects.equals(this.netIncomeBeforeTaxesYear1SUM, financial.netIncomeBeforeTaxesYear1SUM) &&
        Objects.equals(this.netIncomeBeforeTaxesYear2SUM, financial.netIncomeBeforeTaxesYear2SUM) &&
        Objects.equals(this.incomeTaxesYear1, financial.incomeTaxesYear1) &&
        Objects.equals(this.incomeTaxesYear2, financial.incomeTaxesYear2) &&
        Objects.equals(this.netProfitYear1SUM, financial.netProfitYear1SUM) &&
        Objects.equals(this.netProfitYear2SUM, financial.netProfitYear2SUM) &&
        Objects.equals(this.beginningOfYearFinancialsYear1, financial.beginningOfYearFinancialsYear1) &&
        Objects.equals(this.beginningOfYearFinancialsYear2, financial.beginningOfYearFinancialsYear2) &&
        Objects.equals(this.cashFlowOperatingYear1, financial.cashFlowOperatingYear1) &&
        Objects.equals(this.cashFlowOperatingYear2, financial.cashFlowOperatingYear2) &&
        Objects.equals(this.cashFlowInvestingYear1, financial.cashFlowInvestingYear1) &&
        Objects.equals(this.cashFlowInvestingYear2, financial.cashFlowInvestingYear2) &&
        Objects.equals(this.cashFlowFinancingYear1, financial.cashFlowFinancingYear1) &&
        Objects.equals(this.cashFlowFinancingYear2, financial.cashFlowFinancingYear2) &&
        Objects.equals(this.cashFlowYear1SUM, financial.cashFlowYear1SUM) &&
        Objects.equals(this.cashFlowYear2SUM, financial.cashFlowYear2SUM) &&
        Objects.equals(this.endOfYearFinancialsYear1SUM, financial.endOfYearFinancialsYear1SUM) &&
        Objects.equals(this.endOfYearFinancialsYear2SUM, financial.endOfYearFinancialsYear2SUM)&&
        Objects.equals(this.additionalProperties, financial.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(liquidFundsYear1, liquidFundsYear2, accountsReceivableYear1, accountsReceivableYear2, stocksYear1, stocksYear2, currentAssetsOtherYear1, currentAssetsOtherYear2, currentAssetsYear1SUM, currentAssetsYear2SUM, machinesAndSystemsYear1, machinesAndSystemsYear2, facilitiesAndVehicleParkYear1, facilitiesAndVehicleParkYear2, fixedAssetsOtherYear1, fixedAssetsOtherYear2, fixedAssetsYear1SUM, fixedAssetsYear2SUM, accountsPayableYear1, accountsPayableYear2, totalAssetsYear1, totalAssetsYear2, shortTermLoansYear1, shortTermLoansYear2, curentLiabilitiesOtherYear1, curentLiabilitiesOtherYear2, curentLiabilitiesYear1SUM, curentLiabilitiesYear2SUM, longTermLoansYear1, longTermLoansYear2, accrualsYear1, accrualsYear2, longTermLiabilitiesOtherYear1, longTermLiabilitiesOtherYear2, longTermLiabilitiesYear1SUM, longTermLiabilitiesYear2SUM, equityYear1, equityYear2, totalLiabilitiesYear1SUM, totalLiabilitiesYear2SUM, salesProceedsYear1, salesProceedsYear2, costOfGoodsYear1, costOfGoodsYear2, grossProfitYear1SUM, grossProfitYear2SUM, operatingExpensesYear1, operatingExpensesYear2, ebidtaYear1SUM, ebidtaYear2SUM, depreciationYear1, depreciationYear2, ebitYear1SUM, ebitYear2SUM, financialExpensesYear1, financialExpensesYear2, netIncomeBeforeTaxesYear1SUM, netIncomeBeforeTaxesYear2SUM, incomeTaxesYear1, incomeTaxesYear2, netProfitYear1SUM, netProfitYear2SUM, beginningOfYearFinancialsYear1, beginningOfYearFinancialsYear2, cashFlowOperatingYear1, cashFlowOperatingYear2, cashFlowInvestingYear1, cashFlowInvestingYear2, cashFlowFinancingYear1, cashFlowFinancingYear2, cashFlowYear1SUM, cashFlowYear2SUM, endOfYearFinancialsYear1SUM, endOfYearFinancialsYear2SUM, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Financial {\n");
    sb.append("    liquidFundsYear1: ").append(toIndentedString(liquidFundsYear1)).append("\n");
    sb.append("    liquidFundsYear2: ").append(toIndentedString(liquidFundsYear2)).append("\n");
    sb.append("    accountsReceivableYear1: ").append(toIndentedString(accountsReceivableYear1)).append("\n");
    sb.append("    accountsReceivableYear2: ").append(toIndentedString(accountsReceivableYear2)).append("\n");
    sb.append("    stocksYear1: ").append(toIndentedString(stocksYear1)).append("\n");
    sb.append("    stocksYear2: ").append(toIndentedString(stocksYear2)).append("\n");
    sb.append("    currentAssetsOtherYear1: ").append(toIndentedString(currentAssetsOtherYear1)).append("\n");
    sb.append("    currentAssetsOtherYear2: ").append(toIndentedString(currentAssetsOtherYear2)).append("\n");
    sb.append("    currentAssetsYear1SUM: ").append(toIndentedString(currentAssetsYear1SUM)).append("\n");
    sb.append("    currentAssetsYear2SUM: ").append(toIndentedString(currentAssetsYear2SUM)).append("\n");
    sb.append("    machinesAndSystemsYear1: ").append(toIndentedString(machinesAndSystemsYear1)).append("\n");
    sb.append("    machinesAndSystemsYear2: ").append(toIndentedString(machinesAndSystemsYear2)).append("\n");
    sb.append("    facilitiesAndVehicleParkYear1: ").append(toIndentedString(facilitiesAndVehicleParkYear1)).append("\n");
    sb.append("    facilitiesAndVehicleParkYear2: ").append(toIndentedString(facilitiesAndVehicleParkYear2)).append("\n");
    sb.append("    fixedAssetsOtherYear1: ").append(toIndentedString(fixedAssetsOtherYear1)).append("\n");
    sb.append("    fixedAssetsOtherYear2: ").append(toIndentedString(fixedAssetsOtherYear2)).append("\n");
    sb.append("    fixedAssetsYear1SUM: ").append(toIndentedString(fixedAssetsYear1SUM)).append("\n");
    sb.append("    fixedAssetsYear2SUM: ").append(toIndentedString(fixedAssetsYear2SUM)).append("\n");
    sb.append("    accountsPayableYear1: ").append(toIndentedString(accountsPayableYear1)).append("\n");
    sb.append("    accountsPayableYear2: ").append(toIndentedString(accountsPayableYear2)).append("\n");
    sb.append("    totalAssetsYear1: ").append(toIndentedString(totalAssetsYear1)).append("\n");
    sb.append("    totalAssetsYear2: ").append(toIndentedString(totalAssetsYear2)).append("\n");
    sb.append("    shortTermLoansYear1: ").append(toIndentedString(shortTermLoansYear1)).append("\n");
    sb.append("    shortTermLoansYear2: ").append(toIndentedString(shortTermLoansYear2)).append("\n");
    sb.append("    curentLiabilitiesOtherYear1: ").append(toIndentedString(curentLiabilitiesOtherYear1)).append("\n");
    sb.append("    curentLiabilitiesOtherYear2: ").append(toIndentedString(curentLiabilitiesOtherYear2)).append("\n");
    sb.append("    curentLiabilitiesYear1SUM: ").append(toIndentedString(curentLiabilitiesYear1SUM)).append("\n");
    sb.append("    curentLiabilitiesYear2SUM: ").append(toIndentedString(curentLiabilitiesYear2SUM)).append("\n");
    sb.append("    longTermLoansYear1: ").append(toIndentedString(longTermLoansYear1)).append("\n");
    sb.append("    longTermLoansYear2: ").append(toIndentedString(longTermLoansYear2)).append("\n");
    sb.append("    accrualsYear1: ").append(toIndentedString(accrualsYear1)).append("\n");
    sb.append("    accrualsYear2: ").append(toIndentedString(accrualsYear2)).append("\n");
    sb.append("    longTermLiabilitiesOtherYear1: ").append(toIndentedString(longTermLiabilitiesOtherYear1)).append("\n");
    sb.append("    longTermLiabilitiesOtherYear2: ").append(toIndentedString(longTermLiabilitiesOtherYear2)).append("\n");
    sb.append("    longTermLiabilitiesYear1SUM: ").append(toIndentedString(longTermLiabilitiesYear1SUM)).append("\n");
    sb.append("    longTermLiabilitiesYear2SUM: ").append(toIndentedString(longTermLiabilitiesYear2SUM)).append("\n");
    sb.append("    equityYear1: ").append(toIndentedString(equityYear1)).append("\n");
    sb.append("    equityYear2: ").append(toIndentedString(equityYear2)).append("\n");
    sb.append("    totalLiabilitiesYear1SUM: ").append(toIndentedString(totalLiabilitiesYear1SUM)).append("\n");
    sb.append("    totalLiabilitiesYear2SUM: ").append(toIndentedString(totalLiabilitiesYear2SUM)).append("\n");
    sb.append("    salesProceedsYear1: ").append(toIndentedString(salesProceedsYear1)).append("\n");
    sb.append("    salesProceedsYear2: ").append(toIndentedString(salesProceedsYear2)).append("\n");
    sb.append("    costOfGoodsYear1: ").append(toIndentedString(costOfGoodsYear1)).append("\n");
    sb.append("    costOfGoodsYear2: ").append(toIndentedString(costOfGoodsYear2)).append("\n");
    sb.append("    grossProfitYear1SUM: ").append(toIndentedString(grossProfitYear1SUM)).append("\n");
    sb.append("    grossProfitYear2SUM: ").append(toIndentedString(grossProfitYear2SUM)).append("\n");
    sb.append("    operatingExpensesYear1: ").append(toIndentedString(operatingExpensesYear1)).append("\n");
    sb.append("    operatingExpensesYear2: ").append(toIndentedString(operatingExpensesYear2)).append("\n");
    sb.append("    ebidtaYear1SUM: ").append(toIndentedString(ebidtaYear1SUM)).append("\n");
    sb.append("    ebidtaYear2SUM: ").append(toIndentedString(ebidtaYear2SUM)).append("\n");
    sb.append("    depreciationYear1: ").append(toIndentedString(depreciationYear1)).append("\n");
    sb.append("    depreciationYear2: ").append(toIndentedString(depreciationYear2)).append("\n");
    sb.append("    ebitYear1SUM: ").append(toIndentedString(ebitYear1SUM)).append("\n");
    sb.append("    ebitYear2SUM: ").append(toIndentedString(ebitYear2SUM)).append("\n");
    sb.append("    financialExpensesYear1: ").append(toIndentedString(financialExpensesYear1)).append("\n");
    sb.append("    financialExpensesYear2: ").append(toIndentedString(financialExpensesYear2)).append("\n");
    sb.append("    netIncomeBeforeTaxesYear1SUM: ").append(toIndentedString(netIncomeBeforeTaxesYear1SUM)).append("\n");
    sb.append("    netIncomeBeforeTaxesYear2SUM: ").append(toIndentedString(netIncomeBeforeTaxesYear2SUM)).append("\n");
    sb.append("    incomeTaxesYear1: ").append(toIndentedString(incomeTaxesYear1)).append("\n");
    sb.append("    incomeTaxesYear2: ").append(toIndentedString(incomeTaxesYear2)).append("\n");
    sb.append("    netProfitYear1SUM: ").append(toIndentedString(netProfitYear1SUM)).append("\n");
    sb.append("    netProfitYear2SUM: ").append(toIndentedString(netProfitYear2SUM)).append("\n");
    sb.append("    beginningOfYearFinancialsYear1: ").append(toIndentedString(beginningOfYearFinancialsYear1)).append("\n");
    sb.append("    beginningOfYearFinancialsYear2: ").append(toIndentedString(beginningOfYearFinancialsYear2)).append("\n");
    sb.append("    cashFlowOperatingYear1: ").append(toIndentedString(cashFlowOperatingYear1)).append("\n");
    sb.append("    cashFlowOperatingYear2: ").append(toIndentedString(cashFlowOperatingYear2)).append("\n");
    sb.append("    cashFlowInvestingYear1: ").append(toIndentedString(cashFlowInvestingYear1)).append("\n");
    sb.append("    cashFlowInvestingYear2: ").append(toIndentedString(cashFlowInvestingYear2)).append("\n");
    sb.append("    cashFlowFinancingYear1: ").append(toIndentedString(cashFlowFinancingYear1)).append("\n");
    sb.append("    cashFlowFinancingYear2: ").append(toIndentedString(cashFlowFinancingYear2)).append("\n");
    sb.append("    cashFlowYear1SUM: ").append(toIndentedString(cashFlowYear1SUM)).append("\n");
    sb.append("    cashFlowYear2SUM: ").append(toIndentedString(cashFlowYear2SUM)).append("\n");
    sb.append("    endOfYearFinancialsYear1SUM: ").append(toIndentedString(endOfYearFinancialsYear1SUM)).append("\n");
    sb.append("    endOfYearFinancialsYear2SUM: ").append(toIndentedString(endOfYearFinancialsYear2SUM)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("liquidFunds_Year1");
    openapiFields.add("liquidFunds_Year2");
    openapiFields.add("accountsReceivable_Year1");
    openapiFields.add("accountsReceivable_Year2");
    openapiFields.add("stocks_Year1");
    openapiFields.add("stocks_Year2");
    openapiFields.add("currentAssets_Other_Year1");
    openapiFields.add("currentAssets_Other_Year2");
    openapiFields.add("currentAssets_Year1_SUM");
    openapiFields.add("currentAssets_Year2_SUM");
    openapiFields.add("machinesAndSystems_Year1");
    openapiFields.add("machinesAndSystems_Year2");
    openapiFields.add("facilitiesAndVehiclePark_Year1");
    openapiFields.add("facilitiesAndVehiclePark_Year2");
    openapiFields.add("fixedAssets_Other_Year1");
    openapiFields.add("fixedAssets_Other_Year2");
    openapiFields.add("fixedAssets_Year1_SUM");
    openapiFields.add("fixedAssets_Year2_SUM");
    openapiFields.add("accountsPayable_Year1");
    openapiFields.add("accountsPayable_Year2");
    openapiFields.add("totalAssets_Year1");
    openapiFields.add("totalAssets_Year2");
    openapiFields.add("shortTermLoans_Year1");
    openapiFields.add("shortTermLoans_Year2");
    openapiFields.add("curentLiabilities_Other_Year1");
    openapiFields.add("curentLiabilities_Other_Year2");
    openapiFields.add("curentLiabilities_Year1_SUM");
    openapiFields.add("curentLiabilities_Year2_SUM");
    openapiFields.add("longTermLoans_Year1");
    openapiFields.add("longTermLoans_Year2");
    openapiFields.add("accruals_Year1");
    openapiFields.add("accruals_Year2");
    openapiFields.add("longTermLiabilities_Other_Year1");
    openapiFields.add("longTermLiabilities_Other_Year2");
    openapiFields.add("longTermLiabilities_Year1_SUM");
    openapiFields.add("longTermLiabilities_Year2_SUM");
    openapiFields.add("equity_Year1");
    openapiFields.add("equity_Year2");
    openapiFields.add("totalLiabilities_Year1_SUM");
    openapiFields.add("totalLiabilities_Year2_SUM");
    openapiFields.add("salesProceeds_Year1");
    openapiFields.add("salesProceeds_Year2");
    openapiFields.add("costOfGoods_Year1");
    openapiFields.add("costOfGoods_Year2");
    openapiFields.add("grossProfit_Year1_SUM");
    openapiFields.add("grossProfit_Year2_SUM");
    openapiFields.add("operatingExpenses_Year1");
    openapiFields.add("operatingExpenses_Year2");
    openapiFields.add("ebidta_Year1_SUM");
    openapiFields.add("ebidta_Year2_SUM");
    openapiFields.add("depreciation_Year1");
    openapiFields.add("depreciation_Year2");
    openapiFields.add("ebit_Year1_SUM");
    openapiFields.add("ebit_Year2_SUM");
    openapiFields.add("financialExpenses_Year1");
    openapiFields.add("financialExpenses_Year2");
    openapiFields.add("netIncomeBeforeTaxes_Year1_SUM");
    openapiFields.add("netIncomeBeforeTaxes_Year2_SUM");
    openapiFields.add("incomeTaxes_Year1");
    openapiFields.add("incomeTaxes_Year2");
    openapiFields.add("netProfit_Year1_SUM");
    openapiFields.add("netProfit_Year2_SUM");
    openapiFields.add("beginningOfYearFinancials_Year1");
    openapiFields.add("beginningOfYearFinancials_Year2");
    openapiFields.add("cashFlowOperating_Year1");
    openapiFields.add("cashFlowOperating_Year2");
    openapiFields.add("cashFlowInvesting_Year1");
    openapiFields.add("cashFlowInvesting_Year2");
    openapiFields.add("cashFlowFinancing_Year1");
    openapiFields.add("cashFlowFinancing_Year2");
    openapiFields.add("cashFlow_Year1_SUM");
    openapiFields.add("cashFlow_Year2_SUM");
    openapiFields.add("endOfYearFinancials_Year1_SUM");
    openapiFields.add("endOfYearFinancials_Year2_SUM");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Financial
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Financial.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Financial is not found in the empty JSON string", Financial.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Financial.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Financial' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Financial> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Financial.class));

       return (TypeAdapter<T>) new TypeAdapter<Financial>() {
           @Override
           public void write(JsonWriter out, Financial value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Financial read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Financial instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Financial given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Financial
  * @throws IOException if the JSON string is invalid with respect to Financial
  */
  public static Financial fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Financial.class);
  }

 /**
  * Convert an instance of Financial to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

