/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ManualBuilderOption
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ManualBuilderOption {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_INVESTMENT_CURRENTLY = "investmentCurrently";
  @SerializedName(SERIALIZED_NAME_INVESTMENT_CURRENTLY)
  private Double investmentCurrently;

  public static final String SERIALIZED_NAME_ORIGINATORS = "originators";
  @SerializedName(SERIALIZED_NAME_ORIGINATORS)
  private String originators;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "isActive";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  private Boolean isActive;

  public ManualBuilderOption() {
  }

  public ManualBuilderOption id(Integer id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the manual portfolio builder
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "370", value = "Id of the manual portfolio builder")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    
    
    
    this.id = id;
  }


  public ManualBuilderOption investmentCurrently(Double investmentCurrently) {
    
    
    
    
    this.investmentCurrently = investmentCurrently;
    return this;
  }

   /**
   * Current investment using manual autoinvest
   * @return investmentCurrently
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5000", value = "Current investment using manual autoinvest")

  public Double getInvestmentCurrently() {
    return investmentCurrently;
  }


  public void setInvestmentCurrently(Double investmentCurrently) {
    
    
    
    this.investmentCurrently = investmentCurrently;
  }


  public ManualBuilderOption originators(String originators) {
    
    
    
    
    this.originators = originators;
    return this;
  }

   /**
   * Who&#39;s create the manual portfolio builder?
   * @return originators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tom Test", value = "Who's create the manual portfolio builder?")

  public String getOriginators() {
    return originators;
  }


  public void setOriginators(String originators) {
    
    
    
    this.originators = originators;
  }


  public ManualBuilderOption isActive(Boolean isActive) {
    
    
    
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Is manual portfolio builder active? - yes, no
   * @return isActive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Is manual portfolio builder active? - yes, no")

  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    
    
    
    this.isActive = isActive;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ManualBuilderOption instance itself
   */
  public ManualBuilderOption putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManualBuilderOption manualBuilderOption = (ManualBuilderOption) o;
    return Objects.equals(this.id, manualBuilderOption.id) &&
        Objects.equals(this.investmentCurrently, manualBuilderOption.investmentCurrently) &&
        Objects.equals(this.originators, manualBuilderOption.originators) &&
        Objects.equals(this.isActive, manualBuilderOption.isActive)&&
        Objects.equals(this.additionalProperties, manualBuilderOption.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, investmentCurrently, originators, isActive, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManualBuilderOption {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    investmentCurrently: ").append(toIndentedString(investmentCurrently)).append("\n");
    sb.append("    originators: ").append(toIndentedString(originators)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("investmentCurrently");
    openapiFields.add("originators");
    openapiFields.add("isActive");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ManualBuilderOption
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ManualBuilderOption.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ManualBuilderOption is not found in the empty JSON string", ManualBuilderOption.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("originators").isJsonNull() && (jsonObj.get("originators") != null && !jsonObj.get("originators").isJsonNull()) && !jsonObj.get("originators").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `originators` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originators").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ManualBuilderOption.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ManualBuilderOption' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ManualBuilderOption> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ManualBuilderOption.class));

       return (TypeAdapter<T>) new TypeAdapter<ManualBuilderOption>() {
           @Override
           public void write(JsonWriter out, ManualBuilderOption value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ManualBuilderOption read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ManualBuilderOption instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ManualBuilderOption given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ManualBuilderOption
  * @throws IOException if the JSON string is invalid with respect to ManualBuilderOption
  */
  public static ManualBuilderOption fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ManualBuilderOption.class);
  }

 /**
  * Convert an instance of ManualBuilderOption to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

