/*
 * C4C REST API
 * Access to the Crowd4Cash Crowdlending Platform through an API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@crowd4cash.ch
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ConnectorReport;
import com.konfigthis.client.model.IntermediaryReport;
import com.konfigthis.client.model.RentalReport;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportsApi
 */
@Disabled
public class ReportsApiTest {

    private static ReportsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ReportsApi(apiClient);
    }

    /**
     * Get your connector account summary and investments of the connected investors
     *
     * __Note__: It&#39;s valid only for investments made indirectly through connector
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConnectorInvestmentsTest() throws ApiException {
        ConnectorReport response = api.getConnectorInvestments()
                .execute();
        // TODO: test validations
    }

    /**
     * Get your intermediary account summary and your partner loans data
     *
     * __Note__: It&#39;s valid only for loans made indirectly through the intermediary
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getIntermediaryDataTest() throws ApiException {
        IntermediaryReport response = api.getIntermediaryData()
                .execute();
        // TODO: test validations
    }

    /**
     * Get your rental account summary and your loans data
     *
     * __Note__: It&#39;s valid only for loans made through this API
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rentalAccountSummaryTest() throws ApiException {
        RentalReport response = api.rentalAccountSummary()
                .execute();
        // TODO: test validations
    }

}
